/*
 * File: app/view/DCV/addRefs.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.DCV.addRefs', {
    extend: 'Ext.window.Window',
    alias: 'widget.dcv.addrefs',

    requires: [
        'Portal.view.DCV.addRefsViewModel',
        'Ext.form.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.field.Text'
    ],

    viewModel: {
        type: 'dcv.addrefs'
    },
    height: 347,
    width: 488,
    layout: 'fit',
    title: 'Справочник',

    items: [
        {
            xtype: 'form',
            bodyPadding: 10,
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'container',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'MyButton'
                                },
                                {
                                    xtype: 'button',
                                    text: 'MyButton'
                                }
                            ]
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Наименование'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    fieldLabel: 'Имя таблицы в БД',
                    labelWidth: 150
                }
            ]
        }
    ]

});