/*
 * File: app/view/DCV/mainViewController.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.DCV.mainViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.dcv.main',

    onBtnDCVZayavAddClick: function(button, e, eOpts) {
        var ed=Ext.create('Portal.view.DCV.ZayavEdit2');
        ed.down('form').getForm().setValues({id:0,DateInput:new Date()});
        ed.setTitle('Новое заявление');
        ed.show();
    },

    onBtnDCVZayavDelClick: function(button, e, eOpts) {

    },

    onBtnDCVSettingsClick: function(button, e, eOpts) {
        var ed=Ext.create('Portal.view.DCV.Settings');
        //ed.down('form').getForm().setValues({id:0});
        ed.show();
    }

});
