/*
 * File: app/view/DCV/ObjEdit.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.DCV.ObjEdit', {
    extend: 'Ext.window.Window',
    alias: 'widget.dcv.objedit',

    requires: [
        'Portal.view.DCV.ObjEditViewModel',
        'Portal.view.DCV.ObjEditViewController',
        'Ext.form.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Number',
        'Ext.form.FieldSet',
        'Ext.form.field.Date',
        'Ext.grid.Panel',
        'Ext.grid.column.Action',
        'Ext.view.Table',
        'Ext.grid.plugin.CellEditing',
        'Ext.form.field.TextArea',
        'Ext.form.field.Hidden'
    ],

    controller: 'dcv.objedit',
    viewModel: {
        type: 'dcv.objedit'
    },
    modal: true,
    height: 554,
    width: 685,
    layout: 'fit',
    title: 'Объект',
    maximizable: true,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'form',
            reference: 'form',
            scrollable: 'vertical',
            layout: 'fit',
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'container',
                            padding: 10,
                            items: [
                                {
                                    xtype: 'button',
                                    iconCls: 'dialog-save',
                                    text: 'Сохранить',
                                    listeners: {
                                        click: {
                                            fn: 'onSaveClick',
                                            scope: 'controller'
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    iconCls: 'dialog-cancel',
                                    text: 'Отменить',
                                    listeners: {
                                        click: {
                                            fn: 'onCancelClick',
                                            scope: 'controller'
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'tabpanel',
                    bodyPadding: 10,
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            reference: 'Tab0',
                            title: 'Основное',
                            items: [
                                {
                                    xtype: 'container',
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: 'hbox',
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    width: 314,
                                                    fieldLabel: 'Кадастровый номер',
                                                    labelWidth: 120,
                                                    name: 'CadNum'
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    flex: 1,
                                                    padding: '0 0 10 10',
                                                    width: 165,
                                                    fieldLabel: 'Вид объекта',
                                                    labelWidth: 80,
                                                    name: 'ObjectVid',
                                                    editable: false,
                                                    autoLoadOnValue: true,
                                                    displayField: 'name_s',
                                                    valueField: 'id',
                                                    bind: {
                                                        store: '{ObjectVid}'
                                                    },
                                                    listeners: {
                                                        change: 'onComboboxChange'
                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch',
                                                padding: '0 0 10 0'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    fieldLabel: 'Адрес',
                                                    labelWidth: 50,
                                                    name: 'ON_Address'
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    flex: 1,
                                                    reference: 'ON_Ploschad',
                                                    padding: '0 0 0 10',
                                                    fieldLabel: 'Площадь, кв.м',
                                                    name: 'ON_Ploschad',
                                                    listeners: {
                                                        change: {
                                                            fn: 'onON_PloschadChange',
                                                            scope: 'controller'
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    reference: 'BlockZemlya',
                                    title: 'Земельный участок',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            anchor: '100%',
                                            fieldLabel: 'Категория',
                                            editable: false,
                                            autoLoadOnValue: true,
                                            displayField: 'name',
                                            valueField: 'id',
                                            bind: {
                                                store: '{ZemlyaKategory}'
                                            }
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Вид разрешенного использования',
                                            labelAlign: 'top'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    reference: 'BlockOKS',
                                    layout: 'hbox',
                                    title: 'Объект капитального строительства',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            fieldLabel: 'Вид ОКС',
                                            labelWidth: 60,
                                            autoLoadOnValue: true,
                                            displayField: 'name',
                                            valueField: 'id',
                                            bind: {
                                                store: '{OKSVid}'
                                            }
                                        },
                                        {
                                            xtype: 'combobox',
                                            flex: 1,
                                            padding: '0 0 5 10',
                                            fieldLabel: 'Назначение',
                                            labelWidth: 80,
                                            editable: false,
                                            displayField: 'name',
                                            valueField: 'id',
                                            bind: {
                                                store: '{ObjectNaznachenie}'
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    title: 'Заинтересованность',
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: 'hbox',
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    flex: 1,
                                                    name: 'ApplicantType',
                                                    editable: false,
                                                    autoLoadOnValue: true,
                                                    displayField: 'name',
                                                    valueField: 'id',
                                                    bind: {
                                                        store: '{ApplicantType}'
                                                    }
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    flex: 1,
                                                    padding: '0 0 5 10',
                                                    fieldLabel: 'Тип документа',
                                                    name: 'DocsType',
                                                    editable: false,
                                                    autoLoadOnValue: true,
                                                    displayField: 'name',
                                                    valueField: 'id',
                                                    bind: {
                                                        store: '{DocsTypeApplicant}'
                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldset',
                                            layout: 'hbox',
                                            title: 'Документ',
                                            items: [
                                                {
                                                    xtype: 'datefield',
                                                    width: 165,
                                                    fieldLabel: 'Дата',
                                                    labelWidth: 50
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    padding: '0 0 5 10',
                                                    fieldLabel: 'Номер',
                                                    labelWidth: 50
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            reference: 'Tab1',
                            title: 'Кадастровая стоимость',
                            items: [
                                {
                                    xtype: 'container',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'numberfield',
                                                    reference: 'KadStoimost',
                                                    fieldLabel: 'Стоимость, руб',
                                                    name: 'KadStoimost',
                                                    listeners: {
                                                        change: {
                                                            fn: 'onNumberfieldChange',
                                                            scope: 'controller'
                                                        }
                                                    }
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    width: 255,
                                                    fieldLabel: 'Удельный показатель',
                                                    labelWidth: 150
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            layout: {
                                                type: 'vbox',
                                                align: 'center',
                                                padding: '0 0 0 10'
                                            },
                                            items: [
                                                {
                                                    xtype: 'datefield',
                                                    fieldLabel: 'Дата определения',
                                                    labelWidth: 130
                                                },
                                                {
                                                    xtype: 'datefield',
                                                    fieldLabel: 'Дата внесения в ГКН',
                                                    labelWidth: 130
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    title: 'Акт об утверждении кадастровой стоимости',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            flex: 1,
                                            labelWidth: 150,
                                            name: 'DocsUtvCadStoim',
                                            editable: false,
                                            autoLoadOnValue: true,
                                            displayField: 'name',
                                            valueField: 'id',
                                            bind: {
                                                store: '{DocsUtvCadStoim}'
                                            }
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            layout: {
                                                type: 'hbox',
                                                pack: 'center'
                                            },
                                            items: [
                                                {
                                                    xtype: 'datefield',
                                                    width: 175,
                                                    fieldLabel: 'Дата',
                                                    labelWidth: 50
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    padding: '0 0 5 10',
                                                    fieldLabel: 'Номер',
                                                    labelWidth: 50
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'combobox',
                                            flex: 1,
                                            fieldLabel: 'Способ определения',
                                            labelWidth: 150,
                                            editable: false,
                                            autoLoadOnValue: true,
                                            displayField: 'name',
                                            valueField: 'id',
                                            bind: {
                                                store: '{SposobOprCadStiom}'
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    reference: 'blockSRO',
                                    height: 76,
                                    scrollable: 'vertical',
                                    layout: 'form',
                                    title: 'СРО',
                                    items: [
                                        {
                                            xtype: 'gridpanel',
                                            hidden: true,
                                            columns: [
                                                {
                                                    xtype: 'gridcolumn',
                                                    flex: 1,
                                                    dataIndex: 'string',
                                                    text: 'String'
                                                },
                                                {
                                                    xtype: 'actioncolumn',
                                                    dataIndex: 'bool',
                                                    text: 'Boolean',
                                                    items: [
                                                        {
                                                            iconCls: 'icon-delete'
                                                        }
                                                    ]
                                                }
                                            ],
                                            plugins: [
                                                {
                                                    ptype: 'cellediting'
                                                }
                                            ],
                                            dockedItems: [
                                                {
                                                    xtype: 'toolbar',
                                                    dock: 'top',
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            iconCls: 'icon-add',
                                                            text: ''
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            reference: 'ContainerSRO',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    name: 'SRO[]'
                                                },
                                                {
                                                    xtype: 'button',
                                                    iconCls: 'icon-add',
                                                    text: '',
                                                    listeners: {
                                                        click: {
                                                            fn: 'onCSROadd',
                                                            scope: 'controller'
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            reference: 'Tab2',
                            title: 'Рыночная стоимость',
                            items: [
                                {
                                    xtype: 'container',
                                    layout: {
                                        type: 'hbox',
                                        align: 'bottom',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            flex: 1,
                                            fieldLabel: 'Основание определения кадастровой стоимости',
                                            labelAlign: 'top',
                                            autoLoadOnValue: true,
                                            displayField: 'name',
                                            valueField: 'id',
                                            bind: {
                                                store: '{OsnovaniaOpredKadStoim}'
                                            }
                                        },
                                        {
                                            xtype: 'datefield',
                                            padding: '0 0 0 5',
                                            fieldLabel: 'Дата определения<br>рыночной стоимости',
                                            labelAlign: 'top'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    title: 'Стоимость',
                                    layout: {
                                        type: 'hbox',
                                        align: 'bottom',
                                        pack: 'center',
                                        padding: '0 0 5 0'
                                    },
                                    items: [
                                        {
                                            xtype: 'numberfield',
                                            reference: 'RynStoimost',
                                            fieldLabel: 'Рыночная стоимость ОН, руб',
                                            labelAlign: 'top',
                                            name: 'RynStoimost'
                                        },
                                        {
                                            xtype: 'textfield',
                                            reference: 'OneMeterStoimost',
                                            padding: '0 10 0 10',
                                            fieldLabel: 'Стоимость 1 кв.м ОН, руб',
                                            labelAlign: 'top',
                                            name: 'OneMeterStoimost'
                                        },
                                        {
                                            xtype: 'textfield',
                                            reference: 'OtklonenieStoimost',
                                            fieldLabel: 'Отклонение рыночной стоимости<br>от кадастровой, %',
                                            labelAlign: 'top',
                                            name: 'OtklonenieStoimost'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    title: 'Отчет об оценке',
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle',
                                        pack: 'center',
                                        padding: '0 0 5 0'
                                    },
                                    items: [
                                        {
                                            xtype: 'datefield',
                                            fieldLabel: 'Дата',
                                            labelWidth: 50
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            padding: '0 0 0 10',
                                            fieldLabel: 'Номер',
                                            labelWidth: 50
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    padding: '0 5 5 5 ',
                                    title: 'Оценщик',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Ф.И.О.'
                                        },
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    flex: 1,
                                                    fieldLabel: 'СРО'
                                                },
                                                {
                                                    xtype: 'button',
                                                    iconCls: 'icon-add'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    title: 'Экспертное заключение',
                                    items: [
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'middle',
                                                pack: 'center'
                                            },
                                            items: [
                                                {
                                                    xtype: 'datefield',
                                                    fieldLabel: 'Дата',
                                                    labelWidth: 50
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    padding: '0 0 0 10',
                                                    fieldLabel: 'Номер',
                                                    labelWidth: 50
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldset',
                                            padding: '0 5 5 5',
                                            title: 'Эксперты',
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'middle'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            flex: 1,
                                                            fieldLabel: 'Ф.И.О.'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            iconCls: 'icon-add'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            reference: 'Tab3',
                            title: 'Недостоверность сведений',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'Отчет об определении кадастровой стоимости',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch',
                                        padding: '0 5 5 5 '
                                    },
                                    items: [
                                        {
                                            xtype: 'datefield',
                                            fieldLabel: 'Дата',
                                            labelWidth: 50
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            padding: '0 0 0 10',
                                            fieldLabel: 'Номер',
                                            labelWidth: 50
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    title: 'Документ-обоснование недостоверности сведений',
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle',
                                        padding: '0 0 5 0'
                                    },
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'button',
                                            iconCls: 'icon-document-arrow',
                                            text: 'Загрузить'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    title: 'Сведения об ОН при определении его кадастровой стоимости',
                                    items: [
                                        {
                                            xtype: 'textareafield',
                                            anchor: '100%',
                                            fieldLabel: 'Недостоверное сведение (по мнению заявителя)',
                                            labelAlign: 'top'
                                        },
                                        {
                                            xtype: 'textareafield',
                                            anchor: '100%',
                                            fieldLabel: 'Значение',
                                            labelAlign: 'top'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    title: 'Результат рассмотрения заявления комиссией'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'id',
                    listeners: {
                        change: 'onIDfieldChange'
                    }
                },
                {
                    xtype: 'hiddenfield',
                    reference: 'Osnovanie',
                    fieldLabel: 'Label',
                    name: 'Osnovanie',
                    listeners: {
                        change: 'onOsnovanieFieldChange'
                    }
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'idz',
                    listeners: {
                        change: 'onIDZfieldChange'
                    }
                }
            ]
        }
    ],
    listeners: {
        afterrender: {
            fn: 'onWindowAfterRender',
            scope: 'controller'
        }
    },

    onComboboxChange: function(field, newValue, oldValue, eOpts) {
        var ref=this.getReferences();
        if(newValue==1){
            ref.BlockZemlya.setHidden(false);
            ref.BlockOKS.setHidden(true);
        }else{
            ref.BlockZemlya.setHidden(true);
            ref.BlockOKS.setHidden(false);
        }
    },

    onIDfieldChange: function(field, newValue, oldValue, eOpts) {
        console.log('id Obj='+newValue);
    },

    onOsnovanieFieldChange: function(field, newValue, oldValue, eOpts) {
        console.log('Osnovanie='+newValue);
        console.log(this.getReferences().Tab2);

        if(newValue==1){
            this.getReferences().Tab2.setDisabled(true);
        }else if(newValue==2){
            this.getReferences().Tab3.setDisabled(true);
        }
    },

    onIDZfieldChange: function(field, newValue, oldValue, eOpts) {
        console.log('id Zayav='+newValue);
    }

});