/*
 * File: app/view/DCV/ZayavEdit.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.DCV.ZayavEdit', {
    extend: 'Ext.window.Window',
    alias: 'widget.dcv.zayavedit',

    requires: [
        'Portal.view.DCV.ZayavEditViewModel',
        'Portal.view.DCV.ZayavEditViewController',
        'Ext.form.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.view.Table',
        'Ext.tab.Bar'
    ],

    controller: 'dcv.zayavedit',
    viewModel: {
        type: 'dcv.zayavedit'
    },
    modal: true,
    height: 485,
    width: 526,
    layout: 'fit',
    title: 'Новое заявление',
    maximizable: true,

    items: [
        {
            xtype: 'form',
            reference: 'form',
            layout: 'fit',
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'container',
                            padding: 5,
                            layout: 'column',
                            items: [
                                {
                                    xtype: 'button',
                                    reference: 'btnDCVZayavAddLeft',
                                    iconCls: 'icon-arrow-left',
                                    text: 'Назад',
                                    listeners: {
                                        click: 'onBtnDCVZayavAddLeftClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    reference: 'btnDCVZayavAddRight',
                                    iconAlign: 'right',
                                    iconCls: 'icon-arrow-right',
                                    text: 'Вперед',
                                    listeners: {
                                        click: 'onBtnDCVZayavAddRightClick'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'tabpanel',
                    reference: 'TabPanel',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            reference: 'Tab1',
                            layout: 'fit',
                            title: 'Tab 1',
                            items: [
                                {
                                    xtype: 'panel',
                                    layout: 'form'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            reference: 'Tab3',
                            layout: 'fit',
                            title: 'Tab 3',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    title: 'Объекты недвижимости',
                                    columns: [
                                        {
                                            xtype: 'rownumberer'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 159,
                                            dataIndex: 'string',
                                            text: 'Кадастровый номер'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            dataIndex: 'number',
                                            text: 'Вид'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            flex: 1,
                                            dataIndex: 'date',
                                            text: 'Адрес'
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    reference: 'btnObjectAdd',
                                                    disabled: true,
                                                    iconCls: 'icon-add',
                                                    text: 'Добавить',
                                                    listeners: {
                                                        click: 'onBtnObjAddClick'
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    reference: 'btnObjectDel',
                                                    disabled: true,
                                                    iconCls: 'icon-delete',
                                                    text: 'Удалить',
                                                    listeners: {
                                                        click: 'onBtnObjDelClick'
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'bottom',
                                    items: [
                                        {
                                            xtype: 'container',
                                            padding: 10,
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    formBind: true,
                                                    itemId: 'btnDCVZayavAddSave',
                                                    iconCls: 'dialog-save',
                                                    text: 'Сохранить ',
                                                    listeners: {
                                                        click: 'onBtnDCVZayavAddSaveClick'
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'btnDCVZayavAddCancel',
                                                    iconCls: 'dialog-cancel',
                                                    text: 'Отменить',
                                                    listeners: {
                                                        click: 'onBtnDCVZayavAddCancelClick'
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            reference: 'Tab4',
                            title: 'Tab4'
                        }
                    ],
                    tabBar: {
                        xtype: 'tabbar',
                        reference: 'TabBar'
                    }
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onWindowAfterRender'
    }

});