/*
 * File: app/view/DCV/ZayavEdit2.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.DCV.ZayavEdit2', {
    extend: 'Ext.window.Window',
    alias: 'widget.dcv.zayavedit2',

    requires: [
        'Portal.view.DCV.ZayavEdit2ViewModel',
        'Portal.view.DCV.ZayavEdit2ViewController',
        'Ext.form.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.Display',
        'Ext.form.field.Hidden',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.FieldSet',
        'Ext.form.field.Date',
        'Ext.form.field.ComboBox',
        'Ext.form.field.TextArea',
        'Ext.form.RadioGroup',
        'Ext.form.field.Radio'
    ],

    controller: 'dcv.zayavedit2',
    viewModel: {
        type: 'dcv.zayavedit2'
    },
    height: 514,
    width: 524,
    layout: 'fit',
    title: 'My Window',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'form',
            reference: 'form',
            border: false,
            layout: 'fit',
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'container',
                            padding: 10,
                            items: [
                                {
                                    xtype: 'button',
                                    formBind: true,
                                    iconCls: 'dialog-ok',
                                    text: 'Сохранить',
                                    listeners: {
                                        click: {
                                            fn: 'onSaveClick',
                                            scope: 'controller'
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    iconCls: 'dialog-cancel',
                                    text: 'Отменить',
                                    listeners: {
                                        click: {
                                            fn: 'onCloseClick',
                                            scope: 'controller'
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            layout: {
                                type: 'hbox',
                                align: 'stretch',
                                pack: 'end'
                            },
                            items: [
                                {
                                    xtype: 'displayfield',
                                    formBind: true,
                                    fieldLabel: 'ID',
                                    labelWidth: 20,
                                    name: 'idView'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    flex: 1,
                                    reference: 'id',
                                    fieldLabel: 'Label',
                                    name: 'id',
                                    listeners: {
                                        change: 'onHiddenfieldChange'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'tabpanel',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            scrollable: 'vertical',
                            bodyPadding: 10,
                            title: 'Основное',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    height: 69,
                                    layout: 'hbox',
                                    title: 'Заявление',
                                    items: [
                                        {
                                            xtype: 'datefield',
                                            padding: '0 5 0 0',
                                            width: 119,
                                            fieldLabel: 'Дата поступления',
                                            labelAlign: 'top',
                                            labelWidth: 110,
                                            name: 'DateInput',
                                            format: 'Y-m-d'
                                        },
                                        {
                                            xtype: 'combobox',
                                            flex: 1,
                                            formBind: false,
                                            reference: 'Osnovanie',
                                            itemId: 'mycombobox1',
                                            padding: '0 5 0 5',
                                            fieldLabel: 'Основание подачи заявления',
                                            labelAlign: 'top',
                                            name: 'Osnovanie',
                                            allowBlank: false,
                                            editable: false,
                                            autoLoadOnValue: true,
                                            displayField: 'name',
                                            valueField: 'id',
                                            bind: {
                                                store: '{PetitionOsnovaniya}'
                                            },
                                            listeners: {
                                                change: {
                                                    fn: 'onMycombobox1Ch',
                                                    scope: 'controller'
                                                }
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    title: 'Заявитель',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            fieldLabel: 'Статус',
                                            name: 'ApplicantStatus',
                                            allowBlank: false,
                                            editable: false,
                                            autoLoadOnValue: true,
                                            displayField: 'name',
                                            valueField: 'id',
                                            bind: {
                                                store: '{ApplicantStatus}'
                                            },
                                            listeners: {
                                                change: {
                                                    fn: 'onComboboxChange',
                                                    scope: 'controller'
                                                }
                                            }
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'Наименование',
                                            name: 'FIOName',
                                            allowBlank: false
                                        },
                                        {
                                            xtype: 'textfield',
                                            reference: 'OGRN',
                                            hidden: true,
                                            fieldLabel: 'ОГРН',
                                            name: 'OGRN',
                                            maxLength: 13,
                                            minLength: 13,
                                            regex: '^(\d{13})?$'
                                        },
                                        {
                                            xtype: 'textfield',
                                            reference: 'SNILS',
                                            hidden: true,
                                            fieldLabel: 'СНИЛС',
                                            name: 'SNILS'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    title: 'Контактная информация',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            height: 31,
                                            layout: 'hbox',
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    fieldLabel: 'Адрес',
                                                    labelWidth: 50,
                                                    name: 'Address'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            layout: {
                                                type: 'hbox',
                                                pack: 'center'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    height: 53,
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'center'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            fieldLabel: 'Телефон 1',
                                                            name: 'Tel1'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            fieldLabel: 'Телефон 2',
                                                            name: 'Tel2'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    height: 53,
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'center'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            fieldLabel: 'e-mail',
                                                            labelWidth: 50,
                                                            name: 'email'
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            fieldLabel: 'Факс',
                                                            labelWidth: 50,
                                                            name: 'Fax'
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            reference: 'Tab2',
                            layout: 'form',
                            title: 'Статус заявления',
                            items: [
                                {
                                    xtype: 'container',
                                    layout: 'form',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            fieldLabel: 'Статус заявления',
                                            name: 'PetitionStatus',
                                            allowBlank: false,
                                            editable: false,
                                            displayField: 'name',
                                            valueField: 'id',
                                            bind: {
                                                store: '{PetitionStatus}'
                                            },
                                            listeners: {
                                                change: {
                                                    fn: 'onPetitionStatusChange',
                                                    scope: 'controller'
                                                }
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    reference: 'BlockOsnovanie',
                                    layout: 'form',
                                    title: 'Основание',
                                    items: [
                                        {
                                            xtype: 'textareafield',
                                            name: 'OsnovanieOtkaza'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    reference: 'BlockRekvizity',
                                    layout: 'form',
                                    title: 'Реквизиты уведомлений',
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            layout: 'hbox',
                                            title: 'Заявителя',
                                            items: [
                                                {
                                                    xtype: 'datefield',
                                                    width: 165,
                                                    fieldLabel: 'Дата',
                                                    labelWidth: 50,
                                                    name: 'RekvZayavDate',
                                                    format: 'Y-m-d'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    padding: '0 0 10 10',
                                                    fieldLabel: 'Номер',
                                                    labelWidth: 50,
                                                    name: 'RekvZayavNumber'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldset',
                                            layout: 'hbox',
                                            title: 'Органа местного самоуправления',
                                            items: [
                                                {
                                                    xtype: 'datefield',
                                                    width: 165,
                                                    fieldLabel: 'Дата',
                                                    labelWidth: 50,
                                                    name: 'RekvOMSDate',
                                                    format: 'Y-m-d'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    padding: '0 0 10 10',
                                                    fieldLabel: 'Номер',
                                                    labelWidth: 50,
                                                    name: 'RekvOMSNumber'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            bodyPadding: 10,
                            title: 'Результат заседания комиссии',
                            layout: {
                                type: 'vbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'fieldset',
                                    title: 'Соответствие требованиям',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'checkboxgroup',
                                            width: 400,
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'checkboxfield',
                                                    boxLabel: 'Отчет соответствует требованиям статьи 11 153-ФЗ, требованиям ФСО'
                                                },
                                                {
                                                    xtype: 'checkboxfield',
                                                    boxLabel: 'Экспертное заключение соответствует требованиям законодательства РФ'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'radiogroup',
                                    width: 400,
                                    fieldLabel: 'Решение',
                                    layout: {
                                        type: 'vbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'radiofield',
                                            boxLabel: 'Пересмотр'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            boxLabel: 'Определение в размере рыночной стоимости'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            boxLabel: 'Отклонение'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'textareafield',
                                    flex: 1,
                                    fieldLabel: 'Причина отклонения',
                                    labelAlign: 'top'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: 'Tab 3'
                        }
                    ]
                }
            ]
        }
    ],

    onHiddenfieldChange: function(field, newValue, oldValue, eOpts) {
        this.down('form').getForm().setValues({idView:newValue});
    }

});