/*
 * File: app/view/DCV/ZayavEditViewController.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.DCV.ZayavEditViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.dcv.zayavedit',

    onBtnDCVZayavAddLeftClick: function(button, e, eOpts) {
        var ref=this.getReferences(),
            nTab=Number(ref.TabPanel.getActiveTab().getReference()[3]);
        if(nTab==4){
            ref.TabPanel.setActiveTab(2);
            ref.btnDCVZayavAddRight.setHidden(false);
        }else if(nTab==3){
            ref.TabPanel.setActiveTab(1);
        }else if(nTab==2){
            ref.TabPanel.setActiveTab(0);
            ref.btnDCVZayavAddLeft.setHidden(true);
        }else if(nTab==1){}

    },

    onBtnDCVZayavAddRightClick: function(button, e, eOpts) {
        var ref=this.getReferences(),nTab=Number(ref.TabPanel.getActiveTab().getReference()[3]);
        this.ZayavSave();
        ref.TabPanel.setActiveTab(nTab);
        if(nTab==1){
            //Сохраняем Основные данные
            //Возвращаем ID записи
            ref.btnDCVZayavAddLeft.setHidden(false);
        }else if(nTab==3){
            ref.btnDCVZayavAddRight.setHidden(true);
        }
    },

    onBtnObjAddClick: function(button, e, eOpts) {
        var ed=Ext.create('Portal.view.DCV.ObjEdit'),
            r=this.getReferences();
        ed.down('form').getForm().setValues({
            id:0,
            idz:r.id.getValue(),
            Osnovanie:r.Osnovanie.getValue()
        });
        ed.setTitle('Новый объект');
        ed.show();
    },

    onBtnObjDelClick: function(button, e, eOpts) {

    },

    onBtnDCVZayavAddSaveClick: function(button, e, eOpts) {
        this.getView().close();
    },

    onBtnDCVZayavAddCancelClick: function(button, e, eOpts) {
        this.getView().close();
    },

    onWindowAfterRender: function(component, eOpts) {
        var ref=this.getView().getReferences();
        ref.TabBar.setHidden(true);
        ref.BlockOsnovanie.setHidden(true);
        ref.BlockRekvizity.setHidden(true);
        ref.btnDCVZayavAddLeft.setHidden(true);
    }

});
