/*
 * File: app/view/benzine/City_Edit.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.benzine.City_Edit', {
    extend: 'Ext.window.Window',
    alias: 'widget.benzinecity_edit',

    requires: [
        'Portal.view.benzine.City_EditViewModel',
        'Portal.view.benzine.City_EditViewController',
        'Ext.form.Panel',
        'Ext.form.field.Hidden',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    controller: 'benzinecity_edit',
    viewModel: {
        type: 'benzinecity_edit'
    },
    modal: true,
    height: 140,
    width: 400,
    title: 'Введите наименование',

    layout: {
        type: 'vbox',
        align: 'stretch',
        pack: 'end'
    },
    items: [
        {
            xtype: 'form',
            flex: 1,
            reference: 'formCityEdit',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'hiddenfield',
                    anchor: '100%',
                    fieldLabel: 'Label',
                    name: 'id'
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    name: 'name'
                },
                {
                    xtype: 'hiddenfield',
                    anchor: '100%',
                    fieldLabel: 'Label',
                    name: 'new'
                }
            ]
        },
        {
            xtype: 'container',
            layout: {
                type: 'hbox',
                align: 'middle',
                pack: 'end',
                padding: 10
            },
            items: [
                {
                    xtype: 'button',
                    id: 'btnCityEditSave',
                    iconCls: 'dialog-save',
                    text: 'Сохранить',
                    listeners: {
                        click: 'onBtnCityEditSaveClick'
                    }
                },
                {
                    xtype: 'button',
                    id: 'btnCityEditCancel',
                    iconCls: 'dialog-cancel',
                    text: 'Отмена',
                    listeners: {
                        click: 'onBtnCityEditCancelClick'
                    }
                }
            ]
        }
    ]

});