/*
 * File: app/view/sys/setUser/mainViewModel.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.sys.setUser.mainViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.syssetusermain',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.field.Field'
    ],

    stores: {
        orgs: {
            proxy: {
                type: 'ajax',
                url: 'data/sys/setUser/org-read.php',
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                }
            },
            fields: [
                {
                    name: 'id'
                },
                {
                    name: 'name'
                },
                {
                    name: 'name_full'
                }
            ]
        },
        otdels: {
            proxy: {
                type: 'ajax',
                url: 'data/sys/setUser/otdels-list.php',
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                }
            },
            fields: [
                {
                    name: 'id'
                },
                {
                    name: 'code'
                },
                {
                    name: 'name'
                },
                {
                    name: 'sname'
                }
            ]
        },
        dolzhnost: {
            proxy: {
                type: 'ajax',
                url: 'data/sys/setUser/dolzhnost-read.php',
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                }
            },
            fields: [
                {
                    name: 'id'
                },
                {
                    name: 'org_id'
                },
                {
                    name: 'name'
                },
                {
                    name: 'code'
                }
            ]
        },
        address: {
            proxy: {
                type: 'ajax',
                url: 'data/sys/setUser/address-read.php',
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                }
            },
            fields: [
                {
                    name: 'id'
                },
                {
                    name: 'name'
                }
            ]
        }
    }

});