/*
 * File: app/store/EvalEffectives/EvalEffectives.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.store.EvalEffectives.EvalEffectives', {
    extend: 'Ext.data.Store',

    requires: [
        'Portal.model.EvalEffectives.EvalEffectives',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'EvalEffectives.EvalEffectives',
            model: 'Portal.model.EvalEffectives.EvalEffectives',
            proxy: {
                type: 'ajax',
                url: 'data/EvalEffectives/recordData.php',
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                }
            }
        }, cfg)]);
    }
});