/*
 * File: app/view/OpisDel/EditViewController.js
 *
 * This file was generated by Sencha Architect version 4.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.OpisDel.EditViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.opisdel.edit',

    onDateBeginChange: function(field, newValue, oldValue, eOpts) {
        this.getReferences().DateEnd.setMinValue(newValue);
    },

    onDateEndChange: function(field, newValue, oldValue, eOpts) {
        this.getReferences().DateBegin.setMaxValue(newValue);
    },

    onSaveClick: function(button, e, eOpts) {
        var me=this,
            form=me.lookupReference('form'),
            record=form.getRecord(),
            v=form.getValues(),
            store=Ext.getStore('OpisDel.main');

        if (form.isValid()) {
            me.getView().mask('Подождите...');

            if (v.id == '0'){
                var record = Ext.create('Portal.model.OpisDel.main');
                record.set(v);
                store.add(record);
            } else{
                record.set(v);
            }
            store.sync({
                success:function(b,o){
                    store.reload();
                }
            });
            me.getView().unmask();
            me.getView().close();
        }
    },

    onCancelClick: function(button, e, eOpts) {
        this.getView().close();
    },

    onWindowAfterRender: function(component, eOpts) {
        this.getViewModel().getStore('otdels').load();
        var rf=this.getReferences(), dt=new Date();
        rf.form.load({url: 'data/OpisDel/Editor-load.php'});
        rf.DateBegin.setMaxValue(dt);
        rf.DateEnd.setMaxValue(dt);
    }

});
