/*
 * File: app/view/OpisDel/ExportViewController.js
 *
 * This file was generated by Sencha Architect version 4.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.OpisDel.ExportViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.opisdel.export',

    onExportClick: function(button, e, eOpts) {
        var r=this.getReferences();
        window.open('data/OpisDel/report.php?Year='+
        r.Year.getValue()+'&Npp='+r.Npp.getValue());
        this.getView().close();
    },

    onCancelClick: function(button, e, eOpts) {
        this.getView().close();
    },

    onComboboxChange: function(field, newValue, oldValue, eOpts) {
        this.getReferences().form.load({
            url:'data/OpisDel/getNpp.php',
            params:{Year:newValue}
        });
    }

});
