/*
 * File: app/view/OpisDel/Export.js
 *
 * This file was generated by Sencha Architect version 4.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.OpisDel.Export', {
    extend: 'Ext.window.Window',
    alias: 'widget.opisdel.export',

    requires: [
        'Portal.view.OpisDel.ExportViewModel',
        'Portal.view.OpisDel.ExportViewController',
        'Ext.form.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.form.FieldContainer',
        'Ext.button.Button',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Number'
    ],

    controller: 'opisdel.export',
    viewModel: {
        type: 'opisdel.export'
    },
    height: 132,
    resizable: false,
    width: 400,
    layout: 'fit',
    title: 'Экспорт данных в отчет',

    items: [
        {
            xtype: 'form',
            reference: 'form',
            bodyPadding: 10,
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'fieldcontainer',
                            items: [
                                {
                                    xtype: 'button',
                                    formBind: true,
                                    iconCls: 'icon-mime-excel',
                                    text: 'Экспорт',
                                    listeners: {
                                        click: 'onExportClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    iconCls: 'dialog-cancel',
                                    text: 'Отменить',
                                    listeners: {
                                        click: 'onCancelClick'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    reference: 'Year',
                    fieldLabel: 'За год',
                    name: 'Year',
                    allowBlank: false,
                    editable: false,
                    displayField: 'Year',
                    store: 'OpisDel.getYear',
                    valueField: 'Year',
                    listeners: {
                        change: 'onComboboxChange'
                    }
                },
                {
                    xtype: 'numberfield',
                    anchor: '100%',
                    reference: 'Npp',
                    fieldLabel: 'Начальное значение № п/п',
                    labelWidth: 180,
                    name: 'Npp',
                    allowBlank: false
                }
            ]
        }
    ]

});