/*
 * File: app/view/sys/InputFileViewController.js
 * Date: Thu Oct 06 2016 11:09:19 GMT+0200 (RTZ 1 (зима))
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.sys.InputFileViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.sysinputfile',

    onBtnSysInputFileSaveClick: function(button, e, eOpts) {
        var me=this,
            form = me.getReferences('form'),
            values = form.getValues();
        //store = Ext.getStore(values.store);
        if (form.isValid()) {
            me.getView().mask('Подождите...');
            form.submit({
                success: function(form, action) {
                    Ext.Msg.alert('Success', action.result.msg);
                },
                failure: function(form, action) {
                    Ext.Msg.alert('Failed', action.result.msg);
                }
            });
            me.getView().unmask();
            me.getView().close();
        }
    },

    onBtnSysInputFileCancelClick: function(button, e, eOpts) {
        this.getView().close();
    }

});
