/*
 * File: app/view/sys/PortalFAQViewController.js
 * Date: Thu Oct 06 2016 11:09:19 GMT+0200 (RTZ 1 (зима))
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.sys.PortalFAQViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.sysportalfaq',

    onTableItemDblClick: function(dataview, record, item, index, e, eOpts) {
        var edit = Ext.create('Portal.view.sys.PortalFAQEdit').show();
        edit.getReferences().form.getForm().loadRecord(record);
    },

    onTableSelectionChange: function(model, selected, eOpts) {
        var r=this.getReferences();
        r.btnSysPortalFAQDel.setDisabled(selected.length === 0);
        r.btnSysPortalFAQEdit.setDisabled(selected.length === 0);
        console.log(r.gridFAQ.getSelection()[0].id);
    },

    onBtnSysPortalFAQAddClick: function(button, e, eOpts) {
        var edit = Ext.create('Portal.view.sys.PortalFAQEdit').show();
        edit.getReferences().form.getForm().setValues({id:0});
    },

    onBtnSysPortalFAQEditClick: function(button, e, eOpts) {
        var edit = Ext.create('Portal.view.sys.PortalFAQEdit').show();
        edit.getReferences().form.getForm().loadRecord(this.getReferences().gridFAQ.getSelection()[0]);
    },

    onBtnSysPortalFAQDelClick: function(button, e, eOpts) {

    }

});
