/*
 * File: app/view/sys/PortalLoginViewController.js
 * Date: Thu Oct 06 2016 11:09:19 GMT+0200 (RTZ 1 (зима))
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.sys.PortalLoginViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.sys.portallogin',

    onContHeadTextValueAfterRender: function(component, eOpts) {
        component.setValue(PortalName);
    },

    onTextfieldSpecialkey: function(field, e, eOpts) {
        if (e.getKey() === e.ENTER) {
            this.onBtnLoginClick();
        }
    },

    onTextfieldSpecialkey1: function(field, e, eOpts) {
        if (e.getKey() === e.ENTER) {
            this.onBtnLoginClick();
        }
    },

    onComboboxSpecialkey: function(field, e, eOpts) {
        if (e.getKey() === e.ENTER) {
            this.onBtnLoginClick();
        }
    },

    onFormLoginAfterRender: function(component, eOpts) {
        Ext.getStore('PortalDomain').load();
        var r=this.getReferences();
        Ext.Ajax.request({
            url: 'data/PortalSecurity/getlogin.php',
            success: function(res){
                re=Portal.util.Util.decodeJSON(res.responseText);
                r.login.setValue(re.login);
                r.domain.setValue(re.domain);
            }
        });
    },

    onBtnRegsClick: function(button, e, eOpts) {
        Ext.create('Portal.view.PortalRegister');
    },

    onBtnLoginClick: function(button, e, eOpts) {
        var me=this,v=me.getView(),
            ref=me.getReferences(),
            form=ref.formLogin;
        if (form.isValid()) {
            v.mask('Авторизация... Подождите...');
            form.submit({
                clientValidation: true,
                url: 'data/PortalSecurity/login.php',
                scope: me,
                success: function(f, action) {
                    v.unmask();
                    v.close();
                    Ext.create('Portal.view.PortalViewport');
                    //Portal.util.SessionMonitor.start();
                },
                failure: function(form, action) {
                    v.unmask();
                    Portal.util.Util.handleFormFailure(action);
                }
            });
        }
    },

    onResetClick: function(button, e, eOpts) {
        var refs = this.getReferences();
        refs.formLogin.reset();
    },

    onHelpClick: function(button, e, eOpts) {
        Ext.Msg.alert('Краткая помощь', 'Логин и пароль такие же, как при входе в Виндовс');
    }

});
