/*
 * File: app/view/sys/PortalRegisterViewController.js
 * Date: Thu Oct 06 2016 11:09:19 GMT+0200 (RTZ 1 (зима))
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.sys.PortalRegisterViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.sys.portalregister',

    onBtnRegisterClick: function(button, e, eOpts) {
        var me = this,
            form = me.lookupReference('formRegister');
        if (form.isValid()) {

            me.getView().mask('Регистрация... Подождите...');

            form.submit({
                clientValidation: true,
                url: 'data/PortalSecurity/register.php',
                scope: me,
                success: function(form, action) {
                    this.getView().unmask();
                    Portal.util.Util.handleFormSuccess(action);
                    this.getView().close();
                },
                failure: function(form, action) {
                    this.getView().unmask();
                    Portal.util.Util.handleFormFailure(action);
                }
            });
        }
    },

    onBtnCancelClick: function(button, e, eOpts) {
        this.getView().close();

    }

});
