/*
 * File: app/view/sys/PortalNewsEdit.js
 * Date: Thu Oct 06 2016 11:09:19 GMT+0200 (RTZ 1 (зима))
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.sys.PortalNewsEdit', {
    extend: 'Ext.window.Window',
    alias: 'widget.sysportalnewsedit',

    requires: [
        'Portal.view.sys.PortalNewsEditViewModel',
        'Portal.view.sys.PortalNewsEditViewController',
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.form.field.HtmlEditor',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.field.Display',
        'Ext.form.field.Hidden'
    ],

    controller: 'sysportalnewsedit',
    viewModel: {
        type: 'sysportalnewsedit'
    },
    modal: true,
    height: 300,
    width: 540,
    layout: 'fit',
    title: 'Новость',

    items: [
        {
            xtype: 'form',
            reference: 'formNews',
            bodyPadding: 10,
            header: false,
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'textfield',
                    fieldLabel: 'Тема (краткое описание)',
                    labelAlign: 'top',
                    name: 'subject',
                    allowBlank: false,
                    blankText: 'Обязательное поле',
                    maxLength: 250
                },
                {
                    xtype: 'htmleditor',
                    formBind: true,
                    height: 128,
                    name: 'news'
                },
                {
                    xtype: 'hiddenfield',
                    flex: 1,
                    fieldLabel: 'Label',
                    name: 'id'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    padding: 5,
                    items: [
                        {
                            xtype: 'container',
                            padding: 5,
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'btnPortalNewsEditSave',
                                    iconCls: 'dialog-save',
                                    text: 'Сохранить',
                                    listeners: {
                                        click: 'onBtnPortalNewsEditSaveClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    id: 'btnPortalNewsEditCancel',
                                    iconCls: 'dialog-cancel',
                                    text: 'Отмена',
                                    listeners: {
                                        click: 'onBtnPortalNewsEditCancelClick'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            hidden: true,
                            items: [
                                {
                                    xtype: 'displayfield',
                                    fieldLabel: 'Label',
                                    value: 'Display Field'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});