/*
 * File: app/view/sys/tabMainViewViewController.js
 * Date: Thu Oct 06 2016 11:09:19 GMT+0200 (RTZ 1 (зима))
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.sys.tabMainViewViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.sys.tabmainview',

    onBtnPortalTabMainViewNewsAddClick: function(button, e, eOpts) {
        var edit=Ext.create('Portal.view.sys.PortalNewsEdit').show();
        edit.getReferences().formNews.getForm().setValues({id:0});
    },

    onBtnPortalTabMainViewNewsRefreshClick: function(button, e, eOpts) {
        Ext.getStore('sys.PortalNews').reload();
    },

    onBtnPortalTabMainViewNewsDelClick: function(button, e, eOpts) {
        Portal.util.Util.deleteRecord2(
        this.getReferences().panelNews.getSelection()[0],
        Ext.getStore('sys.PortalNews'),
        'data/sys/tabMainNews-delete.php');
    },

    onBtnPortalTabMainViewLinksOnClick: function(button, e, eOpts) {
        this.getReferences().Links.expandAll();
    },

    onBtnPortalTabMainViewLinksOffClick: function(button, e, eOpts) {
        this.getReferences().Links.collapseAll();
    },

    onBtnPortalTabMainViewLinksAdmClick: function(button, e, eOpts) {
        Ext.getStore('PortalLinks').load({
            params:{admin:1}
        });
    },

    onPortalTabMainViewAfterRender: function(component, eOpts) {
        /*********************/
        //this.getReferences().panelCommonInfoToolbar.setHidden(true);
        //this.getReferences().panelCommonInfoHTMLeditor.getToolbar().setHidden(true);
        /*********************/
        var refs = this.getReferences(),
            panelCommonInfo = refs.panelCommonInfo;

        panelCommonInfo.load();


        /***** Устанавливаем права на приложение *****/
        var AccessEdit = Portal.util.Util.appAccessEdit(this.getView().xtype);
        console.log('AccessEdit='+AccessEdit);

        var panelNewsToolbar = this.lookupReference('panelNewsToolbar'),
            panelLinksToolbar = this.lookupReference('panelLinksToolbar'),
            panelCommonInfoTools = this.lookupReference('panelCommonInfoTools');

        panelNewsToolbar.setHidden( !AccessEdit );
        //panelLinksToolbar.setHidden( !AccessEdit );
        panelCommonInfoTools.setHidden( !AccessEdit );

        //this.getReferences().btnPortalTabMainViewLinksAdm.setHidden(!AccessEdit);
        Ext.getStore('sys.PortalNews').load();
    },

    onPanelCommonInfoToolsClick: function(tool, e, owner, eOpts) {
        var refs = this.getReferences(),
            panelCommonInfoHTMLeditor = refs.panelCommonInfoHTMLeditor,
            tb = refs.panelCommonInfoToolbar,
            panelCommonInfoData = refs.panelCommonInfoData;

        if(panelCommonInfoData.isHidden()){//надо закрыть редактор
            //panelCommonInfoHTMLeditor.setValue(owner.body.dom.innerHTML);
            panelCommonInfoHTMLeditor.setHidden(true);
            tb.setHidden(true);
            panelCommonInfoData.setHidden(false);
        }else{ //Включаем редактор
            panelCommonInfoHTMLeditor.setValue(panelCommonInfoData.getValue());
            panelCommonInfoHTMLeditor.setHidden(false);
            tb.setHidden(false);
            panelCommonInfoData.setHidden(true);
        }
    },

    onPanelCommonInfoBtnSaveClick: function(button, e, eOpts) {
        var refs = this.getReferences(),
            form = refs.panelCommonInfo,
            panelCommonInfoHTMLeditor = refs.panelCommonInfoHTMLeditor,
            tb = refs.panelCommonInfoToolbar,
            panelCommonInfoData = refs.panelCommonInfoData;

        panelCommonInfoHTMLeditor.setHidden(true);
        tb.setHidden(true);

        panelCommonInfoData.setValue(panelCommonInfoHTMLeditor.getValue());
        Ext.Ajax.request({
            url: 'data/tabMainCommonInfo.php',
            params: {
                html: panelCommonInfoHTMLeditor.getValue()
            },
            scope: this,
            success: function(conn, response, options, eOpts){
                var result = Portal.util.Util.decodeJSON(conn.responseText);
                if (result.success) {
                } else {
                    Portal.util.Util.showErrorMsg(result.msg);
                }
            },
            failure: function(conn, response, options, eOpts){
                Portal.util.Util.showErrorMsg(conn.responseText);
            }
        });
        panelCommonInfoData.setHidden(false);
    }

});
