/*
 * File: app/view/sys/tabMainView.js
 * Date: Thu Oct 06 2016 11:09:19 GMT+0200 (RTZ 1 (зима))
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.sys.tabMainView', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.sys.tabmainview',

    requires: [
        'Portal.view.sys.tabMainViewViewModel',
        'Portal.view.sys.tabMainViewViewController',
        'Ext.grid.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.plugin.RowExpander',
        'Ext.XTemplate',
        'Ext.grid.column.Action',
        'Ext.tree.Panel',
        'Ext.toolbar.Separator',
        'Ext.tree.View',
        'Ext.tree.Column',
        'Ext.form.Panel',
        'Ext.form.field.Display',
        'Ext.panel.Tool',
        'Ext.form.field.HtmlEditor'
    ],

    controller: 'sys.tabmainview',
    viewModel: {
        type: 'sys.tabmainview'
    },
    reference: 'dashboard',
    id: 'tabMainView_2',
    ui: '2',
    layout: 'border',
    collapsible: false,
    iconCls: 'icon-home',
    title: 'Главная',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'gridpanel',
            region: 'center',
            split: true,
            reference: 'panelNews',
            stateId: 'panelNews',
            stateful: true,
            id: 'panelNews',
            itemId: 'panelNews',
            padding: 5,
            title: 'Новости',
            store: 'sys.PortalNews',
            dockedItems: [
                {
                    xtype: 'toolbar',
                    reference: 'panelNewsToolbar',
                    dock: 'top',
                    id: 'panelNewsToolbar',
                    itemId: 'panelNewsToolbar',
                    items: [
                        {
                            xtype: 'button',
                            id: 'btnPortalTabMainViewNewsAdd',
                            iconCls: 'icon-add',
                            listeners: {
                                click: {
                                    fn: 'onBtnPortalTabMainViewNewsAddClick',
                                    scope: 'controller'
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            id: 'btnPortalTabMainViewNewsRefresh',
                            iconCls: 'icon-refresh',
                            listeners: {
                                click: {
                                    fn: 'onBtnPortalTabMainViewNewsRefreshClick',
                                    scope: 'controller'
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            reference: 'btnPortalTabMainViewNewsDel',
                            disabled: true,
                            id: 'btnPortalTabMainViewNewsDel',
                            iconCls: 'icon-delete',
                            listeners: {
                                click: {
                                    fn: 'onBtnPortalTabMainViewNewsDelClick',
                                    scope: 'controller'
                                }
                            }
                        }
                    ]
                }
            ],
            columns: [
                {
                    xtype: 'rownumberer'
                },
                {
                    xtype: 'gridcolumn',
                    flex: 1,
                    dataIndex: 'subject',
                    text: 'Событие'
                },
                {
                    xtype: 'gridcolumn',
                    width: 140,
                    dataIndex: 'updateDate',
                    text: 'Дата'
                },
                {
                    xtype: 'actioncolumn',
                    width: 25,
                    menuDisabled: true,
                    items: [
                        {
                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                var edit = Ext.create('Portal.view.sys.PortalNewsEdit').show();
                                edit.getReferences().formNews.getForm().setValues(record.data);
                            },
                            iconCls: 'icon-edit'
                        }
                    ]
                }
            ],
            viewConfig: {
                listeners: {
                    selectionchange: 'onTableSelectionChange'
                }
            },
            plugins: [
                {
                    ptype: 'rowexpander',
                    rowBodyTpl: [
                        '{news}',
                        '<hr><span class="ref-NewEdit">Разместил: {userInsert} [{insertDate} {insertTime}]<br>',
                        'Редактировал: {userUpdate} [{updateDate} {updateTime}]</span>'
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'west',
            split: true,
            stateId: 'panelLinks',
            stateful: true,
            itemId: 'panelLinks',
            padding: '5 5 5 5',
            width: 349,
            layout: 'fit',
            items: [
                {
                    xtype: 'treepanel',
                    reference: 'Links',
                    title: 'Ссылки',
                    store: 'PortalLinks',
                    rootVisible: false,
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            reference: 'panelLinksToolbar',
                            dock: 'top',
                            id: 'panelLinksToolbar',
                            itemId: 'panelLinksToolbar',
                            items: [
                                {
                                    xtype: 'button',
                                    id: 'btnPortalTabMainViewLinksOn',
                                    iconCls: 'icon-list-on',
                                    listeners: {
                                        click: {
                                            fn: 'onBtnPortalTabMainViewLinksOnClick',
                                            scope: 'controller'
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    hidden: true,
                                    id: 'btnPortalTabMainViewLinksOff',
                                    iconCls: 'icon-list-off',
                                    listeners: {
                                        click: {
                                            fn: 'onBtnPortalTabMainViewLinksOffClick',
                                            scope: 'controller'
                                        }
                                    }
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    id: 'btnPortalTabMainLinksRefresh',
                                    iconCls: 'icon-refresh',
                                    listeners: {
                                        click: 'onBtnPortalTabMainLinksRefreshClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    reference: 'btnPortalTabMainViewLinksAdm',
                                    hidden: true,
                                    id: 'btnPortalTabMainViewLinksAdm',
                                    iconCls: 'icon-admins',
                                    listeners: {
                                        click: {
                                            fn: 'onBtnPortalTabMainViewLinksAdmClick',
                                            scope: 'controller'
                                        }
                                    }
                                }
                            ]
                        }
                    ],
                    columns: [
                        {
                            xtype: 'treecolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                if(value){
                                    if(record.get('url')){
                                        //  console.log('url='+record.get('url'));
                                        return '<a href="' + record.get('url') + '" target="_blank">' + value + '</a>';
                                    }
                                    return  value ;
                                }
                            },
                            flex: 1,
                            dataIndex: 'name',
                            text: 'Адрес ссылки'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'coment',
                            text: 'Логин/Пароль'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'form',
            region: 'north',
            split: true,
            reference: 'panelCommonInfo',
            stateId: 'panelCommonInfo',
            stateful: true,
            height: 192,
            html: 'TEST',
            id: 'panelCommonInfo',
            itemId: 'panelCommonInfo',
            padding: 5,
            layout: 'fit',
            title: 'Информация',
            url: 'data/tabMainCommonInfo.php',
            items: [
                {
                    xtype: 'displayfield',
                    reference: 'panelCommonInfoData',
                    id: 'panelCommonInfoData',
                    itemId: 'panelCommonInfoData',
                    name: 'html'
                },
                {
                    xtype: 'htmleditor',
                    reference: 'panelCommonInfoHTMLeditor',
                    height: 150,
                    hidden: true,
                    id: 'panelCommonInfoHTMLeditor',
                    itemId: 'panelCommonInfoHTMLeditor',
                    value: '<b>Test</b>'
                }
            ],
            tools: [
                {
                    xtype: 'tool',
                    reference: 'panelCommonInfoTools',
                    id: 'panelCommonInfoTools',
                    itemId: 'panelCommonInfoTools',
                    type: 'gear',
                    listeners: {
                        click: {
                            fn: 'onPanelCommonInfoToolsClick',
                            scope: 'controller'
                        }
                    }
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    reference: 'panelCommonInfoToolbar',
                    dock: 'top',
                    hidden: true,
                    id: 'panelCommonInfoToolbar',
                    itemId: 'panelCommonInfoToolbar',
                    items: [
                        {
                            xtype: 'button',
                            id: 'panelCommonInfoBtnSave',
                            itemId: 'panelCommonInfoBtnSave',
                            iconCls: 'dialog-save',
                            text: 'Сохранить',
                            listeners: {
                                click: {
                                    fn: 'onPanelCommonInfoBtnSaveClick',
                                    scope: 'controller'
                                }
                            }
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        afterrender: {
            fn: 'onPortalTabMainViewAfterRender',
            scope: 'controller'
        }
    },

    onTableSelectionChange: function(model, selected, eOpts) {
        this.getReferences().btnPortalTabMainViewNewsDel.setDisabled(selected.length === 0);
    },

    onBtnPortalTabMainLinksRefreshClick: function(button, e, eOpts) {
        Ext.getStore('PortalLinks').reload();
    }

});