/*
 * File: app/store/sys/setOrgs/Orgs.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.store.sys.setOrgs.Orgs', {
    extend: 'Ext.data.Store',

    requires: [
        'Portal.model.sys.setOrgs.Org',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'sys.setOrgs.Orgs',
            model: 'Portal.model.sys.setOrgs.Org',
            proxy: {
                type: 'ajax',
                url: 'data/sys/setOrgs/orgs-read.php',
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                }
            }
        }, cfg)]);
    }
});