/*
 * File: app/model/EvalEffectives/EvalEffectives.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.model.EvalEffectives.EvalEffectives', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'id'
        },
        {
            name: 'N_planprov'
        },
        {
            name: 'N_plan'
        },
        {
            name: 'N_vyezd'
        },
        {
            name: 'N_doc'
        },
        {
            name: 'N_obsl'
        },
        {
            name: 'N_narush'
        },
        {
            name: 'N_prov'
        },
        {
            name: 'N_provpredp'
        },
        {
            name: 'N_ustr'
        },
        {
            name: 'N_predp'
        },
        {
            name: 'N_195'
        },
        {
            name: 'S_vzysk'
        },
        {
            name: 'S_prist'
        },
        {
            name: 'S_nalozh'
        },
        {
            name: 'N_otm'
        },
        {
            name: 'N_obzh'
        },
        {
            name: 'S_kad'
        },
        {
            name: 'S_zatr'
        },
        {
            name: 'dateInsert'
        },
        {
            name: 'dateUpdate'
        },
        {
            name: 'dateOtchet'
        },
        {
            name: 'userInsert'
        },
        {
            name: 'userUpdate'
        }
    ]
});