/*
 * File: app/controller/Portal.js
 * Date: Thu Oct 06 2016 11:09:22 GMT+0200 (RTZ 1 (зима))
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.controller.Portal', {
    extend: 'Ext.app.Controller',
    alias: 'controller.Portal',

    models: [
        'PortalMenuItem',
        'PortalMenuRoot',
        'sys.PortalDomain',
        'PortalLinks',
        'sys.PortalNews',
        'sys.PortalFAQ'
    ],
    stores: [
        'PortalMenu',
        'PortalDomain',
        'PortalLinks',
        'sys.PortalNews',
        'sys.PortalFAQ'
    ],
    views: [
        'sys.PortalLogin',
        'PortalViewport',
        'sys.PortalHeader',
        'PortalMenu',
        'PortalMenuItem',
        'sys.PortalRegister',
        'sys.PortalNewsEdit',
        'sys.PortalFAQ',
        'sys.PortalFAQEdit',
        'sys.PortalHelp',
        'sys.InputFile'
    ]
});
