/*
 * File: app/view/EvalEffectives/JobersEdit.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.EvalEffectives.JobersEdit', {
    extend: 'Ext.window.Window',
    alias: 'widget.evaleffectivesjobersedit',

    requires: [
        'Portal.view.EvalEffectives.JobersEditViewModel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Hidden'
    ],

    viewModel: {
        type: 'evaleffectivesjobersedit'
    },
    modal: true,
    height: 152,
    width: 493,
    layout: 'fit',
    title: 'Права пользователю',
    defaultListenerScope: true,

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'bottom',
            padding: 5,
            items: [
                {
                    xtype: 'container',
                    padding: 5,
                    items: [
                        {
                            xtype: 'button',
                            iconCls: 'dialog-save',
                            text: 'Сохранить',
                            listeners: {
                                click: 'onButtonClick'
                            }
                        },
                        {
                            xtype: 'button',
                            iconCls: 'dialog-cancel',
                            text: 'Отменить',
                            listeners: {
                                click: 'onButtonClick1'
                            }
                        }
                    ]
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'form',
            reference: 'form',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    reference: 'user',
                    fieldLabel: 'Пользователь',
                    name: 'user',
                    allowBlank: false,
                    editable: false,
                    autoLoadOnValue: true,
                    displayField: 'user',
                    valueField: 'id',
                    bind: {
                        store: '{storeUser}'
                    }
                },
                {
                    xtype: 'combobox',
                    anchor: '100%',
                    reference: 'groupname',
                    fieldLabel: 'Группа',
                    name: 'groupname',
                    allowBlank: false,
                    editable: false,
                    autoLoadOnValue: true,
                    displayField: 'groupname',
                    valueField: 'id',
                    bind: {
                        store: '{storeGroup}'
                    }
                },
                {
                    xtype: 'hiddenfield',
                    anchor: '100%',
                    fieldLabel: 'Label',
                    name: 'id'
                },
                {
                    xtype: 'hiddenfield',
                    anchor: '100%',
                    fieldLabel: 'Label',
                    name: 'user_id'
                },
                {
                    xtype: 'hiddenfield',
                    anchor: '100%',
                    fieldLabel: 'Label',
                    name: 'd_id'
                }
            ]
        }
    ],
    listeners: {
        afterrender: 'onWindowAfterRender'
    },

    onButtonClick: function(button, e, eOpts) {
        var me = this,
            form = me.down('form'),
            values = form.getValues(),
            store = Ext.getStore('EvalEffectives.Jobers');

        if (form.isValid()) {
            me.mask('Подождите...');

            Ext.Ajax.request({
                url: 'data/EvalEffectives/Jobers-edit.php',
                params: values,
                success: function(r) {
                    store.load();
                }
            });
            me.unmask();
            me.close();
        }

    },

    onButtonClick1: function(button, e, eOpts) {
        this.close();
    },

    onWindowAfterRender: function(component, eOpts) {
        //this.getViewModel().getStore('storeUser').load();
        //this.getViewModel().getStore('storeGroup').load();
    }

});