/*
 * File: app/view/EvalEffectives/ParamsEditorViewController.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.EvalEffectives.ParamsEditorViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.evaleffectivesparamseditor',

    onGridpanelSelectionChange: function(model, selected, eOpts) {
        this.getReferences().R2.setValue(
        selected[0].data.R2
        );
    },

    onWindowAfterRender1: function(component, eOpts) {
        this.getView().getReferences().dateParams.setValue(new Date());
    },

    onWindowClose: function(panel, eOpts) {
        //Ext.getStore('EvalEffectives.Record').reload();
    }

});
