/*
 * File: app/view/EvalEffectives/Settings.js
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.EvalEffectives.Settings', {
    extend: 'Ext.window.Window',
    alias: 'widget.evaleffectivessettings',

    requires: [
        'Portal.view.EvalEffectives.SettingsViewModel',
        'Portal.view.EvalEffectives.SettingsViewController',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.grid.Panel',
        'Ext.form.field.Text',
        'Ext.view.Table',
        'Ext.toolbar.Toolbar',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.column.Check',
        'Ext.grid.plugin.RowExpander',
        'Ext.XTemplate',
        'Ext.panel.Tool'
    ],

    controller: 'evaleffectivessettings',
    viewModel: {
        type: 'evaleffectivessettings'
    },
    modal: true,
    height: 496,
    id: 'EvalEffectivesWinSettings',
    width: 740,
    layout: 'fit',
    iconCls: 'icon-setting2',
    title: 'Настройки',
    maximizable: true,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'tabpanel',
            activeTab: 0,
            items: [
                {
                    xtype: 'panel',
                    layout: 'border',
                    title: 'Права доступа',
                    items: [
                        {
                            xtype: 'gridpanel',
                            region: 'west',
                            split: true,
                            reference: 'tblGrAccess',
                            width: 316,
                            title: 'Группы доступа',
                            store: 'EvalEffectives.JobersGroup',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    width: 136,
                                    dataIndex: 'groupname',
                                    text: 'Группа',
                                    editor: {
                                        xtype: 'textfield'
                                    }
                                },
                                {
                                    xtype: 'gridcolumn',
                                    flex: 1,
                                    dataIndex: 'info',
                                    text: 'Описание',
                                    editor: {
                                        xtype: 'textfield'
                                    }
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            iconCls: 'icon-add',
                                            text: 'Добавить',
                                            listeners: {
                                                click: 'onButtonClick'
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            reference: 'btnGrAccessDelete',
                                            disabled: true,
                                            iconCls: 'icon-delete',
                                            text: 'Удалить',
                                            listeners: {
                                                click: 'onButtonClick1'
                                            }
                                        }
                                    ]
                                }
                            ],
                            listeners: {
                                itemdblclick: 'onGridpanelItemDblClick',
                                selectionchange: 'onGridpanelSelectionChange1'
                            }
                        },
                        {
                            xtype: 'gridpanel',
                            region: 'center',
                            reference: 'EvalEffecives_tableSetGrParams',
                            title: 'Параметры для группы',
                            store: 'EvalEffectives.ParamsGroup',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'R1',
                                    text: 'Показатель'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    flex: 1,
                                    dataIndex: 'R2',
                                    text: 'Расшифровка'
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            reference: 'btnGrParamsAdd',
                                            disabled: true,
                                            iconCls: 'icon-add',
                                            text: 'Добавить',
                                            listeners: {
                                                click: 'onButtonClick4'
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            reference: 'btnGrParamsDelete',
                                            disabled: true,
                                            iconCls: 'icon-delete',
                                            text: 'Удалить',
                                            listeners: {
                                                click: 'onButtonClick5'
                                            }
                                        }
                                    ]
                                }
                            ],
                            listeners: {
                                selectionchange: 'onGridpanelSelectionChange2'
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    layout: 'fit',
                    title: 'Пользователи',
                    items: [
                        {
                            xtype: 'gridpanel',
                            reference: 'EvalEffecives_tableSetUsersList',
                            title: 'Пользователи',
                            store: 'EvalEffectives.Jobers',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    flex: 2,
                                    dataIndex: 'user',
                                    text: 'Пользователь'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    flex: 1,
                                    dataIndex: 'groupname',
                                    text: 'Группа'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 172,
                                    dataIndex: 'otdel',
                                    groupable: true,
                                    text: 'Отдел'
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            iconCls: 'icon-add',
                                            text: 'Добавить',
                                            listeners: {
                                                click: 'onButtonClick2'
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            reference: 'btnSetUsersDelete',
                                            disabled: true,
                                            iconCls: 'icon-delete',
                                            text: 'Удалить',
                                            listeners: {
                                                click: 'onButtonClick3'
                                            }
                                        }
                                    ]
                                }
                            ],
                            listeners: {
                                selectionchange: 'onGridpanelSelectionChange',
                                itemdblclick: 'onEvalEffecives_tableSetUsersListItemDblClick'
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    layout: 'border',
                    title: 'Справочники',
                    items: [
                        {
                            xtype: 'gridpanel',
                            region: 'west',
                            split: true,
                            hidden: true,
                            width: 308,
                            title: 'Константы',
                            columns: [
                                {
                                    xtype: 'rownumberer'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    text: 'Константа',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            width: 80,
                                            text: 'Наименование'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            flex: 1,
                                            dataIndex: 'number',
                                            text: 'Расшифровка'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'numbercolumn',
                                    text: 'Значение'
                                },
                                {
                                    xtype: 'datecolumn',
                                    dataIndex: 'date',
                                    text: 'С какой даты<br>действует'
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            iconCls: 'icon-add',
                                            text: 'Добавить'
                                        },
                                        {
                                            xtype: 'button',
                                            iconCls: 'icon-delete',
                                            text: 'Удалить'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'gridpanel',
                            region: 'center',
                            split: true,
                            reference: 'tblCountGZI',
                            title: 'Численность инспекторов в отделах',
                            store: 'EvalEffectives.GZIcount',
                            columns: [
                                {
                                    xtype: 'rownumberer'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    flex: 1,
                                    dataIndex: 'otdel_name',
                                    text: 'Отдел'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 72,
                                    dataIndex: 'n_gzi',
                                    text: 'Кол-во',
                                    format: '0'
                                },
                                {
                                    xtype: 'datecolumn',
                                    dataIndex: 'dateCount',
                                    text: 'С какой даты<br>действует',
                                    format: 'Y-m-d'
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            iconCls: 'icon-add',
                                            text: 'Добавить',
                                            listeners: {
                                                click: 'onButtonClick6'
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            reference: 'btnCalcInspetorDel',
                                            disabled: true,
                                            iconCls: 'icon-delete',
                                            text: 'Удалить',
                                            listeners: {
                                                click: 'onButtonClick7'
                                            }
                                        }
                                    ]
                                }
                            ],
                            listeners: {
                                itemdblclick: 'onGridpanelItemDblClick1',
                                selectionchange: 'onGridpanelSelectionChange5'
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    reference: 'tab4',
                    layout: 'border',
                    title: 'Показатели',
                    items: [
                        {
                            xtype: 'gridpanel',
                            region: 'west',
                            split: true,
                            reference: 'tblParamsIn',
                            width: 291,
                            title: 'Входные показатели',
                            store: 'EvalEffectives.ParamsIn',
                            columns: [
                                {
                                    xtype: 'rownumberer'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'R1',
                                    text: 'Паказатель'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    flex: 1,
                                    dataIndex: 'R2',
                                    text: 'Расшифровка'
                                },
                                {
                                    xtype: 'checkcolumn',
                                    width: 54,
                                    dataIndex: 'on',
                                    text: 'Вкл/Выкл'
                                }
                            ],
                            viewConfig: {
                                width: 224
                            },
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    items: [
                                        {
                                            xtype: 'button',
                                            iconCls: 'icon-add',
                                            text: 'Добавить',
                                            listeners: {
                                                click: 'onButtonClick8'
                                            }
                                        },
                                        {
                                            xtype: 'button',
                                            reference: 'btnTblParamsIn',
                                            disabled: true,
                                            iconCls: 'icon-delete',
                                            text: 'Удалить',
                                            listeners: {
                                                click: 'onButtonClick9'
                                            }
                                        }
                                    ]
                                }
                            ],
                            listeners: {
                                itemdblclick: 'onGridpanelItemDblClick2',
                                selectionchange: 'onGridpanelSelectionChange3'
                            }
                        },
                        {
                            xtype: 'panel',
                            region: 'center',
                            layout: 'border',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    region: 'north',
                                    split: true,
                                    reference: 'tblParamsOut',
                                    height: 150,
                                    title: 'Выходные (вычисляемые) показатели',
                                    store: 'EvalEffectives.ParamsOut',
                                    columns: [
                                        {
                                            xtype: 'rownumberer'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            width: 68,
                                            dataIndex: 'Punkt',
                                            text: 'Пункт<br>документа',
                                            format: '0'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'C1',
                                            text: 'Параметр'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'C2',
                                            text: 'Расшифровка'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            flex: 1,
                                            dataIndex: 'formula',
                                            text: 'Формула'
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    iconCls: 'icon-add',
                                                    text: 'Добавить',
                                                    listeners: {
                                                        click: 'onButtonClick10'
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    reference: 'btnTblParamsOut',
                                                    disabled: true,
                                                    iconCls: 'icon-delete',
                                                    text: 'Удалить',
                                                    listeners: {
                                                        click: 'onButtonClick13'
                                                    }
                                                }
                                            ]
                                        }
                                    ],
                                    plugins: [
                                        {
                                            ptype: 'rowexpander',
                                            rowBodyTpl: [
                                                '<i>{C2}</i>'
                                            ]
                                        }
                                    ],
                                    listeners: {
                                        itemdblclick: 'onGridpanelItemDblClick3'
                                    }
                                },
                                {
                                    xtype: 'gridpanel',
                                    region: 'center',
                                    split: true,
                                    reference: 'tblEffect',
                                    title: 'Показатели эффективности',
                                    store: 'EvalEffectives.ParamsEffectives',
                                    columns: [
                                        {
                                            xtype: 'rownumberer'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'Punkt',
                                            text: 'Пункт<br>документа'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            text: 'Процент эффективности',
                                            columns: [
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'Percent1',
                                                    text: 'С',
                                                    format: '0'
                                                },
                                                {
                                                    xtype: 'numbercolumn',
                                                    dataIndex: 'Percent2',
                                                    text: 'По',
                                                    format: '0'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            dataIndex: 'Effective',
                                            text: 'Балл',
                                            format: '0'
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    iconCls: 'icon-add',
                                                    text: 'Добавить',
                                                    listeners: {
                                                        click: 'onButtonClick11'
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    reference: 'btnTblEffect',
                                                    disabled: true,
                                                    iconCls: 'icon-delete',
                                                    text: 'Удалить',
                                                    listeners: {
                                                        click: 'onButtonClick12'
                                                    }
                                                }
                                            ]
                                        }
                                    ],
                                    listeners: {
                                        itemdblclick: 'onGridpanelItemDblClick4',
                                        selectionchange: 'onGridpanelSelectionChange4'
                                    }
                                }
                            ]
                        }
                    ],
                    listeners: {
                        activate: {
                            fn: 'onPanelActivate',
                            scope: 'controller'
                        }
                    }
                }
            ]
        }
    ],
    listeners: {
        afterrender: {
            fn: 'onEvalEffectivesWinSettingsAfterRender',
            scope: 'controller'
        }
    },
    tools: [
        {
            xtype: 'tool',
            type: 'help',
            listeners: {
                click: 'onToolClick'
            }
        }
    ],

    onButtonClick: function(button, e, eOpts) {
        var ed = Ext.create('Portal.view.EvalEffectives.JobersGroupEdit').show();
        ed.down('form').getForm().setValues({id:0});
    },

    onButtonClick1: function(button, e, eOpts) {
        Portal.util.Util.deleteRecord2(
        this.getReferences().tblGrAccess.getSelection()[0],
        Ext.getStore('EvalEffectives.JobersGroup'),
        'data/EvalEffectives/JobersGroup-delete.php');

    },

    onGridpanelItemDblClick: function(dataview, record, item, index, e, eOpts) {
        var ed = Ext.create('Portal.view.EvalEffectives.JobersGroupEdit').show();
        ed.down('form').getForm().setValues(record.data);
    },

    onGridpanelSelectionChange1: function(model, selected, eOpts) {
        //this.getReferences().btnGrAccessDelete.setDisabled(selected.length === 0);
        this.getReferences().btnGrParamsAdd.setDisabled(selected.length === 0);
        Ext.getStore('EvalEffectives.ParamsGroup').load({params:{
            g_id:selected[0].data.id
        }});
    },

    onButtonClick4: function(button, e, eOpts) {
        var gt=this.getReferences().tblGrAccess.getSelection()[0].data;
        var ed = Ext.create('Portal.view.EvalEffectives.ParamsGroupEdit').show();
        ed.setTitle('Параметр для группы "'+gt.groupname+'"');
        ed.getViewModel().getStore('storeParamsGroup').load({params:{g_id:gt.id}});
        ed.down('form').getForm().setValues({
            id:0,
            g_id:gt.id
        });
    },

    onButtonClick5: function(button, e, eOpts) {
        Portal.util.Util.deleteRecord2(
        this.getReferences().EvalEffecives_tableSetGrParams.getSelection()[0],
        Ext.getStore('EvalEffectives.ParamsGroup'),
        'data/EvalEffectives/ParamsGroup-delete.php');
    },

    onGridpanelSelectionChange2: function(model, selected, eOpts) {
        this.getReferences().btnGrParamsDelete.setDisabled(selected.length === 0);
    },

    onButtonClick2: function(button, e, eOpts) {
        var ed = Ext.create('Portal.view.EvalEffectives.JobersEdit').show();
        ed.down('form').getForm().setValues({id:0});
    },

    onButtonClick3: function(button, e, eOpts) {
        Portal.util.Util.deleteRecord2(
            this.getReferences().EvalEffecives_tableSetUsersList.getSelection()[0],
            Ext.getStore('EvalEffectives.Jobers'),
            'data/EvalEffectives/Jobers-delete.php');
    },

    onGridpanelSelectionChange: function(model, selected, eOpts) {
        this.getReferences().btnSetUsersDelete.setDisabled(selected.length === 0);

    },

    onEvalEffecives_tableSetUsersListItemDblClick: function(dataview, record, item, index, e, eOpts) {
        var ed = Ext.create('Portal.view.EvalEffectives.JobersEdit').show();
        ed.down('form').getForm().setValues(record.data);
    },

    onButtonClick6: function(button, e, eOpts) {
        var ed = Ext.create('Portal.view.EvalEffectives.GZIcount').show();
        ed.down('form').getForm().setValues({id:0});
    },

    onButtonClick7: function(button, e, eOpts) {
        Portal.util.Util.deleteRecord2(
        this.getReferences().tblCountGZI.getSelection()[0],
        Ext.getStore('EvalEffectives.GZIcount'),
        'data/EvalEffectives/CountGZI-delete.php');
    },

    onGridpanelItemDblClick1: function(dataview, record, item, index, e, eOpts) {
        var ed = Ext.create('Portal.view.EvalEffectives.GZIcount').show();
        ed.down('form').getForm().setValues(record.data);
    },

    onGridpanelSelectionChange5: function(model, selected, eOpts) {
        this.getReferences().btnCalcInspetorDel.setDisabled(selected.length === 0);
    },

    onButtonClick8: function(button, e, eOpts) {
        var ed = Ext.create('Portal.view.EvalEffectives.ParamsInEdit').show();
        ed.down('form').getForm().setValues({id:0});
    },

    onButtonClick9: function(button, e, eOpts) {
        Portal.util.Util.deleteRecord2(
        this.getReferences().tblParamsIn.getSelection()[0],
        Ext.getStore('EvalEffectives.ParamsIn'),
        'data/EvalEffectives/ParamsIn-delete.php');
    },

    onGridpanelItemDblClick2: function(dataview, record, item, index, e, eOpts) {
        var ed = Ext.create('Portal.view.EvalEffectives.ParamsInEdit').show();
        ed.down('form').getForm().setValues(record.data);
    },

    onGridpanelSelectionChange3: function(model, selected, eOpts) {
        this.getReferences().btnTblParamsIn.setDisabled(selected.length === 0);
    },

    onButtonClick10: function(button, e, eOpts) {
        var ed = Ext.create('Portal.view.EvalEffectives.ParamsOutEdit').show();
        ed.down('form').getForm().setValues({id:0});
    },

    onButtonClick13: function(button, e, eOpts) {

    },

    onGridpanelItemDblClick3: function(dataview, record, item, index, e, eOpts) {
        var ed = Ext.create('Portal.view.EvalEffectives.ParamsOutEdit').show();
                ed.down('form').getForm().setValues(record.data);
    },

    onButtonClick11: function(button, e, eOpts) {
        var ed = Ext.create('Portal.view.EvalEffectives.ParamsEffectives').show();
        ed.down('form').getForm().setValues({id:0});
    },

    onButtonClick12: function(button, e, eOpts) {
        Portal.util.Util.deleteRecord2(
        this.getReferences().tblEffect.getSelection()[0],
        Ext.getStore('EvalEffectives.ParamsEffectives'),
        'data/EvalEffectives/ParamsEffectives-delete.php');
    },

    onGridpanelItemDblClick4: function(dataview, record, item, index, e, eOpts) {
        var ed = Ext.create('Portal.view.EvalEffectives.ParamsEffectives').show();
        ed.down('form').getForm().setValues(record.data);
    },

    onGridpanelSelectionChange4: function(model, selected, eOpts) {
        this.getReferences().btnTblEffect.setDisabled(selected.length === 0);
    },

    onToolClick: function(tool, e, owner, eOpts) {
        Ext.Msg.show({
            title:'Help meeeee!..',
            message: 'Для каждой группы доступа выбираем отдельный параметр для ввода.<br>Параметры не должны повторяться!',
            buttons: Ext.Msg.OK,
            icon: Ext.Msg.INFO,
            fn: function(btn) {
                if (btn === 'yes') {
                    console.log('Yes pressed');
                } else if (btn === 'no') {
                    console.log('No pressed');
                } else {
                    console.log('Cancel pressed');
                }
            }
        });
    }

});