/*
 * File: app/view/PhonesBook/PhonesBook.js
 *
 * This file was generated by Sencha Architect version 4.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.PhonesBook.PhonesBook', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.PhonesBook',

    requires: [
        'Portal.view.PhonesBook.PhonesBookViewModel',
        'Portal.view.PhonesBook.PhonesBookViewController',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.form.Panel',
        'Ext.form.field.Checkbox',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.field.Text',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.column.Action',
        'Ext.grid.column.Number',
        'Ext.grid.feature.Grouping',
        'Ext.XTemplate'
    ],

    controller: 'PhonesBook',
    viewModel: {
        type: 'PhonesBook'
    },
    stateId: 'PhonesBook',
    autoShow: true,
    height: 549,
    width: 717,
    layout: 'border',
    collapsible: true,
    title: 'Телефонная книга',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'gridpanel',
            region: 'west',
            split: true,
            reference: 'OrgsList',
            width: 236,
            collapsible: true,
            title: 'Организации',
            store: 'PhonesBook.Orgs',
            viewConfig: {
                listeners: {
                    selectionchange: 'onTableSelectionChange'
                }
            },
            dockedItems: [
                {
                    xtype: 'form',
                    reference: 'pnTools',
                    disabled: true,
                    dock: 'bottom',
                    height: 107,
                    padding: '10 10 10 10',
                    width: 100,
                    bodyBorder: false,
                    collapsed: false,
                    collapsible: false,
                    title: '',
                    titleCollapse: false,
                    layout: {
                        type: 'table',
                        columns: 1
                    },
                    items: [
                        {
                            xtype: 'checkboxfield',
                            reference: 'MissingUsers',
                            padding: '5 5 5 5',
                            boxLabel: 'Показывать отсутсвтующих',
                            listeners: {
                                change: 'onMissingUsersChange'
                            }
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    iconCls: 'icon-mime-excel-16',
                                    text: 'Excel',
                                    listeners: {
                                        click: 'onButtonClick4'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    iconCls: 'icon-printer',
                                    text: 'Печать',
                                    listeners: {
                                        click: 'onButtonClick'
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'toolbar',
                    reference: 'tbOrgEdit',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            disabled: true,
                            iconCls: 'icon-add',
                            text: 'Добавить'
                        },
                        {
                            xtype: 'button',
                            reference: 'btnOrgDel',
                            disabled: true,
                            iconCls: 'icon-delete',
                            text: 'Удалить'
                        }
                    ]
                }
            ],
            columns: [
                {
                    xtype: 'gridcolumn',
                    flex: 1,
                    dataIndex: 'name',
                    text: 'Наименование'
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'center',
            split: false,
            layout: 'border',
            header: false,
            title: 'My Panel',
            dockedItems: [
                {
                    xtype: 'toolbar',
                    reference: 'tbUserEdit',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'checkboxfield',
                            reference: 'showAllUsers',
                            disabled: true,
                            boxLabel: 'Показать всех',
                            listeners: {
                                change: 'onCheckboxfieldChange'
                            }
                        },
                        {
                            xtype: 'button',
                            reference: 'btnUserAdd',
                            disabled: true,
                            iconCls: 'icon-add',
                            text: 'Добавить',
                            listeners: {
                                click: 'onButtonClick1'
                            }
                        },
                        {
                            xtype: 'button',
                            reference: 'btnUserDel',
                            disabled: true,
                            iconCls: 'icon-delete',
                            text: 'Удалить',
                            listeners: {
                                click: 'onButtonClick2'
                            }
                        },
                        {
                            xtype: 'button',
                            reference: 'btnUserEdit',
                            disabled: true,
                            iconCls: 'icon-edit',
                            text: 'Редактировать',
                            listeners: {
                                click: 'onButtonClick3'
                            }
                        }
                    ]
                },
                {
                    xtype: 'toolbar',
                    flex: 1,
                    dock: 'top',
                    items: [
                        {
                            xtype: 'textfield',
                            flex: 1,
                            reference: 'seek',
                            disabled: true,
                            width: 359,
                            name: 'SearchField',
                            emptyText: 'Поиск...',
                            enableKeyEvents: true,
                            listeners: {
                                change: 'onSeekChange'
                            }
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'gridpanel',
                    region: 'center',
                    reference: 'UserList',
                    stateId: 'UsersList',
                    autoShow: true,
                    header: false,
                    store: 'PhonesBook.UsersStore',
                    viewConfig: {
                        getRowClass: function(record, rowIndex, rowParams, store) {
                            var $r='user-on';
                            if(record.get('say')==='0'){
                                $r='user-nosay';
                            }
                            else if(record.get('off')!=='0'){
                                $r='user-off';
                            }
                            return $r;
                        },
                        listeners: {
                            selectionchange: 'onTableSelectionChange1'
                        }
                    },
                    columns: [
                        {
                            xtype: 'rownumberer',
                            dataIndex: '',
                            text: ''
                        },
                        {
                            xtype: 'actioncolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                this.items[0].icon=value;
                            },
                            reference: 'PictColumn',
                            draggable: false,
                            resizable: false,
                            width: 43,
                            align: 'center',
                            dataIndex: 'userImageSrc',
                            text: 'Pict'
                        },
                        {
                            xtype: 'gridcolumn',
                            flex: 2,
                            width: 207,
                            dataIndex: 'FIO',
                            text: 'Ф.И.О.'
                        },
                        {
                            xtype: 'numbercolumn',
                            width: 47,
                            dataIndex: 'telIP',
                            text: 'Тел IP',
                            format: '0000'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 100,
                            sortable: true,
                            dataIndex: 'tel1',
                            text: 'Тел 1'
                        },
                        {
                            xtype: 'gridcolumn',
                            flex: 1,
                            hidden: true,
                            sortable: true,
                            dataIndex: 'otdel_name',
                            groupable: true,
                            text: 'Отдел'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 125,
                            dataIndex: 'dolzhnost_name',
                            text: 'Должность'
                        },
                        {
                            xtype: 'numbercolumn',
                            hidden: true,
                            dataIndex: 'dolzhnost_code',
                            text: 'Должность(код)',
                            format: '0'
                        }
                    ],
                    features: [
                        {
                            ftype: 'grouping',
                            showSummaryRow: true
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            hidden: true,
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    boxLabel: 'группировка по отделам',
                                    listeners: {
                                        change: 'onCheckboxfieldChange1'
                                    }
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'south',
                    split: true,
                    reference: 'detailInfo',
                    height: 220,
                    scrollable: true,
                    tpl: [
                        '<img src="{userImageSrc}" style="float: right" height="64" width="64"/>',
                        '',
                        '<b>{FIO}</b>',
                        '<tpl if="say == 0">',
                        '     <span class="user-nosay"> *** Не отображается в справочнике ***</span>',
                        '</tpl>',
                        '',
                        '<br>',
                        '<tpl if="off == 2">',
                        '    - <span class="user-off">Отсутствует с <span style="color:red">{dateOff}</span> по <span style="color:red">{dateOn}</span></span>',
                        '</tpl>',
                        '<hr>',
                        '{dolzhnost_name}<br>',
                        '{otdel_name}<br>',
                        '<hr>',
                        '{address_name}',
                        '<hr>',
                        'Тел IP: {telIP}<br>',
                        'Тел 1: {tel1}<br>',
                        'Тел 2: {tel2}<br>',
                        'email: {email}<br>',
                        '',
                        '<!--a href="{wiki}" target="_blank"></a><br>',
                        '{price:usMoney}<br-->',
                        '<!--img src="data/{img}" style="float: right" /-->',
                        ''
                    ],
                    bodyPadding: 10,
                    collapsible: true,
                    title: 'Детальная информация'
                }
            ]
        }
    ],
    listeners: {
        show: {
            fn: 'onPanelShow',
            scope: 'controller'
        },
        afterrender: {
            fn: 'onPanelAfterRender',
            scope: 'controller'
        }
    },

    onTableSelectionChange: function(model, selected, eOpts) {
        var ref=this.getReferences();
        //ref.btnOrgDel.setDisabled(selected.length === 0);
        ref.btnUserAdd.setDisabled(selected.length === 0);
        ref.btnUserEdit.setDisabled(true);
        ref.seek.setDisabled(false);
        ref.showAllUsers.setDisabled(false);
        ref.showAllUsers.setValue(false);
        ref.pnTools.setDisabled(false);
        ref.seek.setValue("");
        this.getController().ShowUsers("");
    },

    onMissingUsersChange: function(field, newValue, oldValue, eOpts) {
        this.getController().ShowUsers("");
        this.getReferences().seek.setValue("");
    },

    onButtonClick4: function(button, e, eOpts) {
        //Ext.exporter.excel.Xlsx.setConfig({});
        /*var ug=this.getReferences().UserList;
        ug.saveDocumentAs({
             type: 'excel',
             title: 'My export',
             fileName: 'myExport.xlsx'
         });
        */


        var exporter = Ext.Factory.exporter({
            type: 'excel',
            data: {
                columns: [{
                    text: 'Vacation',
                    columns: [
                        { text: 'Month', width: 200, style: { alignment: { horizontal: 'Right' } } },
                        { text: 'Days', style: { format: 'General Number' } }
                    ]
                }],
                groups: [{
                    text: 'Employees',
                    groups: [{
                        text: 'Adrian',
                        rows: [{
                            cells: [
                                { value: 'January' },
                                { value: 2 }
                            ]
                        },{
                            cells: [
                                { value: 'July' },
                                { value: 10 }
                            ]
                        }],
                        summaries: [{
                            cells: [
                                { value: 'Total' },
                                { value: 12 }
                            ]
                        }]
                    },{
                        text: 'John',
                        rows: [{
                            cells: [
                                { value: 'March' },
                                { value: 4 }
                            ]
                        },{
                            cells: [
                                { value: 'May' },
                                { value: 4 }
                            ]
                        },{
                            cells: [
                                { value: 'July' },
                                { value: 2 }
                            ]
                        }],
                        summaries: [{
                            cells: [
                                { value: 'Total' },
                                { value: 10 }
                            ]
                        }]
                    }],
                    summaries: [{
                        cells: [
                            { value: 'Grand total' },
                            { value: 22 }
                        ]
                    }]
                }]
            }
        });

        // save the file
        exporter.saveAs().then( function() { exporter.destroy(); } );

    },

    onButtonClick: function(button, e, eOpts) {
        var r=this.getReferences(),
            grid=r.UserList,
        Org=r.OrgsList.getView().getSelectionModel().getSelection()[0];
        Ext.ux.grid.Printer.printAutomatically = false;
        Ext.ux.grid.Printer.mainTitle = 'Телефонный справочник организации "'+Org.get('name')+'"';
        r.PictColumn.hide();
        Ext.ux.grid.Printer.print(grid);
        r.PictColumn.show();
    },

    onCheckboxfieldChange: function(field, newValue, oldValue, eOpts) {
        var r=this.getReferences();
        this.getController().ShowUsers(r.seek.getValue());
        if(newValue){r.MissingUsers.setValue(true);}
    },

    onButtonClick1: function(button, e, eOpts) {
        var ed = Ext.create('Portal.view.PhonesBook.UserEdit');
        ed.down('form').getForm().setValues({
            id:'p-0',
            org_id:this.getReferences().OrgsList.getSelection()[0].data.id
        });
        ed.show();
    },

    onButtonClick2: function(button, e, eOpts) {
        Portal.util.Util.deleteRecord2(
            {id:this.getReferences().UserList.getSelection()[0].data.id.substr(2)},
        Ext.getStore('PhonesBook.UsersStore'),
        'data/PhonesBook/user-delete.php');
    },

    onButtonClick3: function(button, e, eOpts) {
        var ed = Ext.create('Portal.view.PhonesBook.UserEdit');
        ed.down('form').getForm().setValues(
            this.getReferences().UserList.getSelection()[0].data
        );
        ed.show();
    },

    onSeekChange: function(field, newValue, oldValue, eOpts) {
        this.getController().ShowUsers(newValue);
    },

    onTableSelectionChange1: function(model, selected, eOpts) {
        var r=this.getReferences(),
            rus=r.UserList.getSelection()[0];
        if(rus){
            if(rus.data.id.substr(0,1)!='u'){
                r.btnUserDel.setDisabled(selected.length === 0);
            }else{r.btnUserDel.setDisabled(true);}
        }
        r.btnUserEdit.setDisabled(selected.length === 0);
        if(selected.length){r.detailInfo.update(selected[0].data);}
    },

    onCheckboxfieldChange1: function(field, newValue, oldValue, eOpts) {
        console.log(newValue);
    }

});