/*
 * File: app/view/DCV/main.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.DCV.main', {
    extend: 'Ext.window.Window',
    alias: 'widget.dcv.main',

    requires: [
        'Portal.view.DCV.mainViewModel',
        'Portal.view.DCV.mainViewController',
        'Ext.toolbar.Toolbar',
        'Ext.container.ButtonGroup',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean',
        'Ext.view.Table'
    ],

    controller: 'dcv.main',
    viewModel: {
        type: 'dcv.main'
    },
    autoShow: true,
    height: 452,
    width: 666,
    layout: 'fit',
    title: 'DisputCadastralValue',
    maximizable: true,

    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            items: [
                {
                    xtype: 'buttongroup',
                    title: 'Редактор',
                    columns: 2,
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'btnDCVZayavAdd',
                            iconCls: 'icon-add',
                            text: 'Добавить',
                            listeners: {
                                click: 'onBtnDCVZayavAddClick'
                            }
                        },
                        {
                            xtype: 'button',
                            itemId: 'btnDCVZayavDel',
                            iconCls: 'icon-delete',
                            text: 'Удалить',
                            listeners: {
                                click: 'onBtnDCVZayavDelClick'
                            }
                        }
                    ]
                },
                {
                    xtype: 'buttongroup',
                    title: 'Buttons',
                    columns: 2,
                    items: [
                        {
                            xtype: 'button',
                            itemId: 'btnDCVSettings',
                            iconCls: 'icon-setting',
                            text: 'Настройки',
                            listeners: {
                                click: 'onBtnDCVSettingsClick'
                            }
                        },
                        {
                            xtype: 'button',
                            text: 'Button 2'
                        }
                    ]
                }
            ]
        }
    ],
    items: [
        {
            xtype: 'gridpanel',
            title: 'Информация о работе комиссий',
            columns: [
                {
                    xtype: 'rownumberer'
                },
                {
                    xtype: 'datecolumn',
                    width: 69,
                    dataIndex: 'date',
                    text: 'Дата'
                },
                {
                    xtype: 'gridcolumn',
                    text: 'Заявитель',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: 64,
                            text: 'Статус'
                        },
                        {
                            xtype: 'gridcolumn',
                            flex: 1,
                            width: 110,
                            text: 'ФИО/Наименование'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'number',
                            text: 'Адрес'
                        }
                    ]
                },
                {
                    xtype: 'booleancolumn',
                    width: 114,
                    dataIndex: 'bool',
                    text: 'Статус заявления'
                }
            ]
        }
    ]

});