/*
 * File: app/view/DCV/SettingsViewModel.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.DCV.SettingsViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.dcv.settings',

    requires: [
        'Ext.data.Store',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.field.Field',
        'Ext.data.writer.Json'
    ],

    stores: {
        refs: {
            proxy: {
                type: 'ajax',
                url: 'data/DCV/refs-list.php',
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                }
            },
            fields: [
                {
                    name: 'id'
                },
                {
                    name: 'name'
                },
                {
                    name: 'reference'
                }
            ]
        },
        refer: {
            proxy: {
                type: 'ajax',
                api: {
                    create: 'data/DCV/refer-new.php',
                    read: 'data/DCV/refer-read.php',
                    update: 'data/DCV/refer-upd.php',
                    destroy: 'data/DCV/refer-del.php'
                },
                url: 'data/DCV/refer-read.php',
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                },
                writer: {
                    type: 'json',
                    writeAllFields: true,
                    encode: true,
                    rootProperty: 'data'
                }
            },
            fields: [
                {
                    name: 'id'
                }
            ]
        },
        fields: {
            proxy: {
                type: 'ajax',
                url: 'data/DCV/table_fld-read.php',
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                }
            },
            fields: [
                {
                    name: 'dataIndex'
                },
                {
                    name: 'name'
                },
                {
                    name: 'tooltip'
                },
                {
                    name: 'header'
                },
                {
                    name: 'xtype'
                }
            ]
        }
    }

});