/*
 * File: app/view/DCV/ZayavEditViewController.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.DCV.ZayavEditViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.dcv.zayavedit',

    ZayavSave: function(a, b) {
        var me=this,ref=me.getReferences(),
        f=me.getView().down('form').getForm(),v=f.getValues(),
        nTab=ref.TabPanel.getActiveTab().getReference()[3];
        //Сохраняем Основные данные
        //Возвращаем ID записи


        //st=Ext.getStore('EvalEffectives.ParamsOut');
        //if(f.isValid()) {
        me.getView().mask('Подождите...');
        Ext.Ajax.request({
            url:'data/DCV/ZayavEdit-post.php',
            params:v,
            success:function(r){//st.reload();
                //console.log( Portal.util.Util.decodeJSON( r.responseText ) );
                f.setValues({id:Portal.util.Util.decodeJSON(r.responseText).data });
            },
            failure:function(r,o){Ext.Msg.alert('ERROR!',r);}
        });
        me.getView().unmask();
    },

    onBtnDCVZayavAddLeftClick: function(button, e, eOpts) {
        var ref=this.getReferences(),
            nTab=Number(ref.TabPanel.getActiveTab().getReference()[3]);
        if(nTab==4){
            ref.TabPanel.setActiveTab(2);
            ref.btnDCVZayavAddRight.setHidden(false);
        }else if(nTab==3){
            ref.TabPanel.setActiveTab(1);
        }else if(nTab==2){
            ref.TabPanel.setActiveTab(0);
            ref.btnDCVZayavAddLeft.setHidden(true);
        }else if(nTab==1){}

    },

    onBtnDCVZayavAddRightClick: function(button, e, eOpts) {
        var ref=this.getReferences(),nTab=Number(ref.TabPanel.getActiveTab().getReference()[3]);
        this.ZayavSave();
        ref.TabPanel.setActiveTab(nTab);
        if(nTab==1){
            //Сохраняем Основные данные
            //Возвращаем ID записи
            ref.btnDCVZayavAddLeft.setHidden(false);
        }else if(nTab==3){
            ref.btnDCVZayavAddRight.setHidden(true);
        }
    },

    onMycombobox1Ch: function(field, newValue, oldValue, eOpts) {
        if(newValue>=1){this.getReferences().btnObjectAdd.setDisabled(false);}
    },

    onComboboxChange: function(field, newValue, oldValue, eOpts) {
        var ref=this.getReferences();
        //console.log(newValue);
        if(newValue==1){//Физ.Лицо
            ref.OGRN.setHidden(true);
            ref.SNILS.setVisible(true);
        }else{
            ref.SNILS.setHidden(true);
            ref.OGRN.setVisible(true);
        }
    },

    onPetitionStatusChange: function(field, newValue, oldValue, eOpts) {
        var r=this.getReferences();
        if(newValue==1){
            r.BlockOsnovanie.setHidden(true);
            r.BlockRekvizity.setHidden(false);
        }else if(newValue==2){
            r.BlockOsnovanie.setHidden(false);
            r.BlockRekvizity.setHidden(true);
        }else if(newValue==3){
            r.BlockOsnovanie.setHidden(false);
            r.BlockRekvizity.setHidden(true);
        }

    },

    onBtnObjAddClick: function(button, e, eOpts) {
        var ed=Ext.create('Portal.view.DCV.ObjEdit'),
            r=this.getReferences();
        ed.down('form').getForm().setValues({
            id:0,
            idz:r.id.getValue(),
            Osnovanie:r.Osnovanie.getValue()
        });
        ed.setTitle('Новый объект');
        ed.show();
    },

    onBtnObjDelClick: function(button, e, eOpts) {

    },

    onBtnDCVZayavAddSaveClick: function(button, e, eOpts) {
        this.getView().close();
    },

    onBtnDCVZayavAddCancelClick: function(button, e, eOpts) {
        this.getView().close();
    },

    onWindowAfterRender: function(component, eOpts) {
        var ref=this.getView().getReferences();
        ref.TabBar.setHidden(true);
        ref.BlockOsnovanie.setHidden(true);
        ref.BlockRekvizity.setHidden(true);
        ref.btnDCVZayavAddLeft.setHidden(true);
    }

});
