/*
 * File: app/view/DCV/ZayavEdit.js
 *
 * This file was generated by Sencha Architect version 4.1.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.DCV.ZayavEdit', {
    extend: 'Ext.window.Window',
    alias: 'widget.dcv.zayavedit',

    requires: [
        'Portal.view.DCV.ZayavEditViewModel',
        'Portal.view.DCV.ZayavEditViewController',
        'Ext.form.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.Display',
        'Ext.form.field.Hidden',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.form.FieldSet',
        'Ext.form.field.Date',
        'Ext.form.field.ComboBox',
        'Ext.form.field.TextArea',
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.view.Table',
        'Ext.tab.Bar'
    ],

    controller: 'dcv.zayavedit',
    viewModel: {
        type: 'dcv.zayavedit'
    },
    modal: true,
    height: 380,
    width: 526,
    layout: 'fit',
    title: 'Новое заявление',
    maximizable: true,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'form',
            reference: 'form',
            layout: 'fit',
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'container',
                            padding: 5,
                            layout: 'column',
                            items: [
                                {
                                    xtype: 'button',
                                    reference: 'btnDCVZayavAddLeft',
                                    itemId: 'btnDCVZayavAddLeft',
                                    iconCls: 'icon-arrow-left',
                                    text: 'Назад',
                                    listeners: {
                                        click: {
                                            fn: 'onBtnDCVZayavAddLeftClick',
                                            scope: 'controller'
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    reference: 'btnDCVZayavAddRight',
                                    itemId: 'btnDCVZayavAddRight',
                                    iconAlign: 'right',
                                    iconCls: 'icon-arrow-right',
                                    text: 'Вперед',
                                    listeners: {
                                        click: {
                                            fn: 'onBtnDCVZayavAddRightClick',
                                            scope: 'controller'
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                type: 'hbox',
                                align: 'stretch',
                                pack: 'end'
                            },
                            items: [
                                {
                                    xtype: 'displayfield',
                                    formBind: true,
                                    fieldLabel: 'ID',
                                    labelWidth: 20,
                                    name: 'idView'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    flex: 1,
                                    reference: 'id',
                                    fieldLabel: 'Label',
                                    name: 'id',
                                    listeners: {
                                        change: 'onHiddenfieldChange'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'tabpanel',
                    reference: 'TabPanel',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            reference: 'Tab1',
                            layout: 'fit',
                            title: 'Tab 1',
                            items: [
                                {
                                    xtype: 'panel',
                                    layout: 'form',
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            height: 69,
                                            layout: 'hbox',
                                            title: 'Заявление',
                                            items: [
                                                {
                                                    xtype: 'datefield',
                                                    padding: '0 5 0 0',
                                                    width: 119,
                                                    fieldLabel: 'Дата поступления',
                                                    labelAlign: 'top',
                                                    labelWidth: 110,
                                                    name: 'DateInput',
                                                    format: 'Y-m-d'
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    flex: 1,
                                                    formBind: false,
                                                    reference: 'Osnovanie',
                                                    itemId: 'mycombobox1',
                                                    padding: '0 5 0 5',
                                                    fieldLabel: 'Основание подачи заявления',
                                                    labelAlign: 'top',
                                                    name: 'Osnovanie',
                                                    allowBlank: false,
                                                    editable: false,
                                                    autoLoadOnValue: true,
                                                    displayField: 'name',
                                                    valueField: 'id',
                                                    bind: {
                                                        store: '{PetitionOsnovaniya}'
                                                    },
                                                    listeners: {
                                                        change: {
                                                            fn: 'onMycombobox1Ch',
                                                            scope: 'controller'
                                                        }
                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldset',
                                            title: 'Заявитель',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'combobox',
                                                    fieldLabel: 'Статус',
                                                    name: 'ApplicantStatus',
                                                    allowBlank: false,
                                                    editable: false,
                                                    autoLoadOnValue: true,
                                                    displayField: 'name',
                                                    valueField: 'id',
                                                    bind: {
                                                        store: '{ApplicantStatus}'
                                                    },
                                                    listeners: {
                                                        change: {
                                                            fn: 'onComboboxChange',
                                                            scope: 'controller'
                                                        }
                                                    }
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    fieldLabel: 'Наименование',
                                                    name: 'FIOName',
                                                    allowBlank: false
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    reference: 'OGRN',
                                                    hidden: true,
                                                    fieldLabel: 'ОГРН',
                                                    name: 'OGRN',
                                                    maxLength: 13,
                                                    minLength: 13,
                                                    regex: '^(\d{13})?$'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    reference: 'SNILS',
                                                    hidden: true,
                                                    fieldLabel: 'СНИЛС',
                                                    name: 'SNILS'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldset',
                                            title: 'Контактная информация',
                                            layout: {
                                                type: 'vbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    height: 31,
                                                    layout: 'hbox',
                                                    items: [
                                                        {
                                                            xtype: 'textfield',
                                                            flex: 1,
                                                            fieldLabel: 'Адрес',
                                                            labelWidth: 50,
                                                            name: 'Address'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    layout: {
                                                        type: 'hbox',
                                                        pack: 'center'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'container',
                                                            height: 53,
                                                            layout: {
                                                                type: 'vbox',
                                                                align: 'center'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'textfield',
                                                                    fieldLabel: 'Телефон 1',
                                                                    name: 'Tel1'
                                                                },
                                                                {
                                                                    xtype: 'textfield',
                                                                    fieldLabel: 'Телефон 2',
                                                                    name: 'Tel2'
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'container',
                                                            flex: 1,
                                                            height: 53,
                                                            layout: {
                                                                type: 'vbox',
                                                                align: 'center'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'textfield',
                                                                    fieldLabel: 'e-mail',
                                                                    labelWidth: 50,
                                                                    name: 'email'
                                                                },
                                                                {
                                                                    xtype: 'textfield',
                                                                    fieldLabel: 'Факс',
                                                                    labelWidth: 50,
                                                                    name: 'Fax'
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            reference: 'Tab2',
                            layout: 'form',
                            title: 'Tab 2',
                            items: [
                                {
                                    xtype: 'container',
                                    layout: 'form',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            fieldLabel: 'Статус заявления',
                                            name: 'PetitionStatus',
                                            allowBlank: false,
                                            editable: false,
                                            displayField: 'name',
                                            valueField: 'id',
                                            bind: {
                                                store: '{PetitionStatus}'
                                            },
                                            listeners: {
                                                change: {
                                                    fn: 'onPetitionStatusChange',
                                                    scope: 'controller'
                                                }
                                            }
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    reference: 'BlockOsnovanie',
                                    layout: 'form',
                                    title: 'Основание',
                                    items: [
                                        {
                                            xtype: 'textareafield',
                                            name: 'OsnovanieOtkaza'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    reference: 'BlockRekvizity',
                                    layout: 'form',
                                    title: 'Реквизиты уведомлений',
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            layout: 'hbox',
                                            title: 'Заявителя',
                                            items: [
                                                {
                                                    xtype: 'datefield',
                                                    width: 165,
                                                    fieldLabel: 'Дата',
                                                    labelWidth: 50,
                                                    name: 'RekvZayavDate',
                                                    format: 'Y-m-d'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    padding: '0 0 10 10',
                                                    fieldLabel: 'Номер',
                                                    labelWidth: 50,
                                                    name: 'RekvZayavNumber'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'fieldset',
                                            layout: 'hbox',
                                            title: 'Органа местного самоуправления',
                                            items: [
                                                {
                                                    xtype: 'datefield',
                                                    width: 165,
                                                    fieldLabel: 'Дата',
                                                    labelWidth: 50,
                                                    name: 'RekvOMSDate',
                                                    format: 'Y-m-d'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    padding: '0 0 10 10',
                                                    fieldLabel: 'Номер',
                                                    labelWidth: 50,
                                                    name: 'RekvOMSNumber'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            reference: 'Tab3',
                            layout: 'fit',
                            title: 'Tab 3',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    title: 'Объекты недвижимости',
                                    columns: [
                                        {
                                            xtype: 'rownumberer'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 159,
                                            dataIndex: 'string',
                                            text: 'Кадастровый номер'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            dataIndex: 'number',
                                            text: 'Вид'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            flex: 1,
                                            dataIndex: 'date',
                                            text: 'Адрес'
                                        }
                                    ],
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    reference: 'btnObjectAdd',
                                                    disabled: true,
                                                    iconCls: 'icon-add',
                                                    text: 'Добавить',
                                                    listeners: {
                                                        click: {
                                                            fn: 'onBtnObjAddClick',
                                                            scope: 'controller'
                                                        }
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    reference: 'btnObjectDel',
                                                    disabled: true,
                                                    iconCls: 'icon-delete',
                                                    text: 'Удалить',
                                                    listeners: {
                                                        click: {
                                                            fn: 'onBtnObjDelClick',
                                                            scope: 'controller'
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'bottom',
                                    items: [
                                        {
                                            xtype: 'container',
                                            padding: 10,
                                            items: [
                                                {
                                                    xtype: 'button',
                                                    formBind: true,
                                                    itemId: 'btnDCVZayavAddSave',
                                                    iconCls: 'dialog-save',
                                                    text: 'Сохранить ',
                                                    listeners: {
                                                        click: {
                                                            fn: 'onBtnDCVZayavAddSaveClick',
                                                            scope: 'controller'
                                                        }
                                                    }
                                                },
                                                {
                                                    xtype: 'button',
                                                    itemId: 'btnDCVZayavAddCancel',
                                                    iconCls: 'dialog-cancel',
                                                    text: 'Отменить',
                                                    listeners: {
                                                        click: {
                                                            fn: 'onBtnDCVZayavAddCancelClick',
                                                            scope: 'controller'
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            reference: 'Tab4',
                            title: 'Tab4'
                        }
                    ],
                    tabBar: {
                        xtype: 'tabbar',
                        reference: 'TabBar'
                    }
                }
            ]
        }
    ],
    listeners: {
        afterrender: {
            fn: 'onWindowAfterRender',
            scope: 'controller'
        }
    },

    onHiddenfieldChange: function(field, newValue, oldValue, eOpts) {
        this.down('form').getForm().setValues({idView:newValue});
    }

});