/*
 * File: app/view/PortalMenuItem.js
 * Date: Thu Oct 06 2016 11:09:19 GMT+0200 (RTZ 1 (зима))
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.PortalMenuItem', {
    extend: 'Ext.tree.Panel',
    alias: 'widget.portalmenuitem',

    requires: [
        'Portal.view.PortalMenuItemViewModel',
        'Portal.view.PortalMenuItemViewController'
    ],

    controller: 'portalmenuitem',
    viewModel: {
        type: 'portalmenuitem'
    },
    border: false,
    scrollable: true,
    title: '',
    rootVisible: false,

    listeners: {
        itemclick: 'onTreepanelItemClick'
    }

});