/*
 * File: app/view/PortalMenuItemViewController.js
 * Date: Thu Oct 06 2016 11:09:19 GMT+0200 (RTZ 1 (зима))
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.PortalMenuItemViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.portalmenuitem',

    onTreepanelItemClick: function(dataview, record, item, index, e, eOpts) {
        console.log("ClassName="+record.data.className+" ** index="+index+" ** id="+record.data.id+" ** text="+record.get('text'));
        var mainPanel = Ext.getCmp('PortalMainPanel');
        var newTab = mainPanel.items.findBy(
        function (tab){
            return tab.title === record.get('text');
        }
        );
        if (!newTab){
            newTab = mainPanel.add({
                xtype: record.data.className,
                closable: true,
                iconCls: record.get('iconCls'),
                title: record.get('text'),
                id: record.data.className+'_'+record.data.id
            });
        }
        mainPanel.setActiveTab(newTab);
    }

});
