/*
 * File: app/view/PortalViewport.js
 * Date: Thu Oct 06 2016 13:26:58 GMT+0200 (RTZ 1 (зима))
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.PortalViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.portalviewport',

    requires: [
        'Portal.view.PortalViewportViewModel',
        'Portal.view.sys.tabMainView',
        'Portal.view.sys.PortalHeader',
        'Portal.view.sys.PortalFAQ',
        'Portal.view.PortalMenu',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.menu.DatePicker'
    ],

    viewModel: {
        type: 'portalviewport'
    },
    stateId: 'Portal',
    stateful: true,
    id: 'portalviewport',
    itemId: 'portalviewport',
    layout: 'border',

    items: [
        {
            xtype: 'tabpanel',
            region: 'center',
            split: true,
            reference: 'MainPanel',
            stateId: 'PortalMainPanel',
            stateful: true,
            id: 'PortalMainPanel',
            itemId: 'PortalMainPanel',
            bodyCls: 'portal-home-body',
            bodyPadding: 2,
            header: false,
            title: 't',
            items: [
                {
                    xtype: 'sys.tabmainview',
                    frameHeader: false,
                    tabConfig: {
                        xtype: 'tab',
                        iconCls: 'icon-home'
                    }
                }
            ]
        },
        {
            xtype: 'sys.portalheader',
            itemId: 'appHeader',
            region: 'north'
        },
        {
            xtype: 'sysportalfaq',
            stateId: 'panelFAQ',
            stateful: true,
            layout: 'fit',
            title: 'Насущные вопросы',
            region: 'east',
            split: true
        },
        {
            xtype: 'panel',
            region: 'west',
            split: true,
            width: 185,
            layout: 'border',
            collapsible: true,
            iconCls: 'home',
            title: 'Навигатор',
            items: [
                {
                    xtype: 'portalmenu',
                    stateId: 'LeftPanel',
                    region: 'center'
                },
                {
                    xtype: 'panel',
                    region: 'south',
                    height: 230,
                    layout: 'fit',
                    collapsed: true,
                    collapsible: true,
                    title: 'Календарь',
                    items: [
                        {
                            xtype: 'datemenu',
                            floating: false
                        }
                    ]
                }
            ]
        }
    ]

});