/*
 * File: app/view/PortalMenuViewController.js
 * Date: Tue Oct 11 2016 11:41:05 GMT+0200 (RTZ 1 (зима))
 *
 * This file was generated by Sencha Architect
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.PortalMenuViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.portalmenu',

    onPanelRender: function(component, eOpts) {
        //console.log('=>'+component);
        Ext.getStore('PortalMenu').load(function(records, op, success){

            var menuPanel = Ext.ComponentQuery.query('portalmenu')[0];
            //this.getReferences().PortalMenu;

            Ext.each(records, function(root){

                var menu = Ext.create('Portal.view.PortalMenuItem',{
                    title: root.get('title'),
                    iconCls: root.get('iconCls')
                });

                Ext.each(root.items(), function(itens){

                    Ext.each(itens.data.items, function(item){

                        menu.getRootNode().appendChild({
                            text: item.get('text'),
                            leaf: true,
                            iconCls: item.get('iconCls'),
                            id: item.get('id'),
                            className: item.get('className')
                        });
                    });
                });

                menuPanel.add(menu);
            });
            //menuPanel.select();
        });
    }

});
