/*
 * File: app/view/Refusals/EditViewController.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.Refusals.EditViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.refusalsedit',

    onBtnRefusalsEditSaveClick: function(button, e, eOpts) {
        var me = this,
            form = me.lookupReference('Form'),
            values = form.getValues(),
            store = Ext.getStore('Refusals.main');

        if (form.isValid()) {
            form.submit({
                url: 'data/Refusals/table-edit.php',
                target : '_blank',
                waitMsg: 'Загружаю документ...',
                success: function(fp,o) {
                    console.log(o.result);
                    store.load();
                    me.getView().close();
                },
                failure: function(fp,o) {
                    console.log(fp);
                    console.log(o.result);
                    store.load();
                    me.getView().close();
                }
            });
        }
    }

});
