/*
 * File: app/view/sys/setOrgs/main.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.sys.setOrgs.main', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.syssetorgs',

    requires: [
        'Portal.view.sys.setOrgs.mainViewModel',
        'Portal.view.sys.setOrgs.mainViewController',
        'Ext.grid.Panel',
        'Ext.grid.column.RowNumberer',
        'Ext.view.Table',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.grid.column.Number'
    ],

    controller: 'syssetorgsmain',
    viewModel: {
        type: 'syssetorgsmain'
    },
    autoShow: true,
    height: 498,
    id: 'syssetorgs',
    width: 591,
    layout: 'border',
    title: 'My Panel',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'gridpanel',
            region: 'north',
            split: true,
            height: 219,
            id: 'setOrgsListOrgs',
            title: 'Список организаций',
            store: 'sys.setOrgs.Orgs',
            columns: [
                {
                    xtype: 'rownumberer'
                },
                {
                    xtype: 'gridcolumn',
                    width: 270,
                    dataIndex: 'name',
                    text: 'Краткое наименование'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'name_full',
                    text: 'Полное наименование',
                    flex: 1
                },
                {
                    xtype: 'gridcolumn',
                    width: 131,
                    dataIndex: 'domain',
                    text: 'Домен'
                }
            ],
            listeners: {
                itemclick: {
                    fn: 'onSetOrgsListOrgsItemClick',
                    scope: 'controller'
                },
                itemdblclick: {
                    fn: 'onSetOrgsListOrgsItemDblClick',
                    scope: 'controller'
                }
            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            iconCls: 'icon-add',
                            text: 'Добавить',
                            listeners: {
                                click: 'onButtonClick'
                            }
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            iconCls: 'icon-delete',
                            text: 'Удалить'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'panel',
            region: 'center',
            split: true,
            layout: 'border',
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    region: 'west',
                    split: true,
                    id: 'setOrgsListOtdels',
                    width: 345,
                    title: 'Структура организации (Отделы)',
                    store: 'sys.setOrgs.Otdels',
                    columns: [
                        {
                            xtype: 'rownumberer'
                        },
                        {
                            xtype: 'numbercolumn',
                            width: 35,
                            align: 'center',
                            dataIndex: 'code',
                            text: 'Order',
                            format: '0'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'name',
                            text: 'Наименование отдела',
                            flex: 1
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 123,
                            dataIndex: 'cn',
                            text: 'cn'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'info',
                            text: 'Доп.Инфо'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    iconCls: 'icon-add',
                                    text: 'Добавить'
                                },
                                {
                                    xtype: 'button',
                                    disabled: true,
                                    iconCls: 'icon-delete',
                                    text: 'Удалить'
                                }
                            ]
                        }
                    ],
                    listeners: {
                        itemdblclick: {
                            fn: 'onSetOrgsListOtdelsItemDblClick',
                            scope: 'controller'
                        }
                    }
                },
                {
                    xtype: 'gridpanel',
                    region: 'center',
                    title: 'Структура организации (Должности)',
                    store: 'sys.setOrgs.Posts',
                    columns: [
                        {
                            xtype: 'rownumberer'
                        },
                        {
                            xtype: 'numbercolumn',
                            width: 33,
                            align: 'center',
                            dataIndex: 'code',
                            text: 'Order',
                            format: '0'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'name',
                            text: 'String',
                            flex: 1
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    iconCls: 'icon-add',
                                    text: 'Добавить'
                                },
                                {
                                    xtype: 'button',
                                    disabled: true,
                                    iconCls: 'icon-delete',
                                    text: 'Удалить'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],
    listeners: {
        activate: {
            fn: 'onSyssetorgsActivate',
            scope: 'controller'
        }
    },

    onButtonClick: function(button, e, eOpts) {
        var ed = Ext.create('Portal.view.sys.setOrgs.OrgEdit').show();
        ed.down('form').getForm().setValues({id:0});
    }

});