/*
 * File: app/view/sys/setOrgs/mainViewController.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.sys.setOrgs.mainViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.syssetorgsmain',

    onSetOrgsListOrgsItemClick: function(dataview, record, item, index, e, eOpts) {
        Ext.getStore('sys.setOrgs.Otdels').load({params:{
            domain:record.data.domain,
            domain_id:record.data.id
        }});
        Ext.getStore('sys.setOrgs.Posts').load({params:{
            domain:record.data.domain,
            domain_id:record.data.id
        }});
    },

    onSetOrgsListOrgsItemDblClick: function(dataview, record, item, index, e, eOpts) {
        var ed = Ext.create('Portal.view.sys.setOrgs.OrgEdit').show();
        ed.down('form').getForm().setValues(record.data);
    },

    onSetOrgsListOtdelsItemDblClick: function(dataview, record, item, index, e, eOpts) {
        var ed = Ext.create('Portal.view.sys.setOrgs.OtdelEdit').show();
        ed.down('form').getForm().setValues(record.data);
    },

    onSyssetorgsActivate: function(component, eOpts) {
        Ext.getStore('sys.setOrgs.Orgs').load();
    }

});
