/*
 * File: app/view/sys/setOrgs/OrgEdit.js
 *
 * This file was generated by Sencha Architect version 3.5.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.view.sys.setOrgs.OrgEdit', {
    extend: 'Ext.window.Window',
    alias: 'widget.syssetorgsorgedit',

    requires: [
        'Portal.view.sys.setOrgs.OrgEditViewModel',
        'Portal.view.sys.setOrgs.OrgEditViewController',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Text',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.form.field.Hidden'
    ],

    controller: 'syssetorgsorgedit',
    viewModel: {
        type: 'syssetorgsorgedit'
    },
    height: 460,
    resizable: false,
    width: 552,
    layout: 'fit',
    title: 'Организация',
    modal: true,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'form',
            reference: 'form',
            bodyPadding: 10,
            items: [
                {
                    xtype: 'fieldset',
                    height: 76,
                    layout: 'form',
                    title: 'Наименование',
                    items: [
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Краткое',
                            name: 'name',
                            allowBlank: false
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Полное',
                            name: 'name_full'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    title: 'Привязка к домену',
                    items: [
                        {
                            xtype: 'container',
                            layout: {
                                type: 'hbox',
                                align: 'middle',
                                padding: 3
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Домен',
                                    name: 'domain'
                                },
                                {
                                    xtype: 'textfield',
                                    padding: '0 0 0 15',
                                    fieldLabel: 'suffix',
                                    labelWidth: 50,
                                    name: 'ad_suffix'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            layout: {
                                type: 'hbox',
                                align: 'middle',
                                padding: 3
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'IP адрес контроллера',
                                    labelWidth: 130,
                                    name: 'ad_ip'
                                },
                                {
                                    xtype: 'textfield',
                                    padding: '0 0 0 15',
                                    width: 120,
                                    fieldLabel: 'Порт',
                                    labelWidth: 50,
                                    name: 'ad_port'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            layout: {
                                type: 'hbox',
                                align: 'middle',
                                padding: 3
                            },
                            items: [
                                {
                                    xtype: 'textfield',
                                    width: 220,
                                    fieldLabel: 'Логин',
                                    name: 'ad_admin'
                                },
                                {
                                    xtype: 'textfield',
                                    padding: '0 0 0 15',
                                    width: 220,
                                    fieldLabel: 'Пароль',
                                    name: 'ad_password',
                                    inputType: 'password'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            layout: 'form',
                            items: [
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'base_dn',
                                    name: 'ad_base_dn'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            title: 'Параметры поиска групп отделов организации',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'group_dn',
                                    name: 'ad_group_dn'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'prefixOtdel',
                                    name: 'ad_prefixOtdel'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            title: 'Параметры поиска пользователей организации',
                            items: [
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    fieldLabel: 'user_dn',
                                    name: 'ad_user_dn'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'hiddenfield',
                    anchor: '100%',
                    fieldLabel: 'Label',
                    name: 'id'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    layout: {
                        type: 'hbox',
                        padding: 10
                    },
                    items: [
                        {
                            xtype: 'container',
                            items: [
                                {
                                    xtype: 'button',
                                    iconCls: 'dialog-save',
                                    text: 'Сохранить',
                                    listeners: {
                                        click: {
                                            fn: 'onButtonClick',
                                            scope: 'controller'
                                        }
                                    }
                                },
                                {
                                    xtype: 'button',
                                    iconCls: 'dialog-cancel',
                                    text: 'Отменить',
                                    listeners: {
                                        click: 'onButtonClick1'
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],

    onButtonClick1: function(button, e, eOpts) {
        this.close();
    }

});