/*
 * File: app/store/PhonesBook/UsersStore.js
 *
 * This file was generated by Sencha Architect version 4.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.2.x Classic library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.2.x Classic. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Portal.store.PhonesBook.UsersStore', {
    extend: 'Ext.data.Store',
    alias: 'store.UsersStore',

    requires: [
        'Portal.model.PhonesBook.UserData',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            groupField: 'otdel_name',
            storeId: 'PhonesBook.UsersStore',
            autoLoad: false,
            model: 'Portal.model.PhonesBook.UserData',
            proxy: {
                type: 'ajax',
                url: 'data/PhonesBook/users.json.php',
                reader: {
                    type: 'json',
                    rootProperty: 'data'
                }
            }
        }, cfg)]);
    }
});